// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AdsZone.proto

package io.union.wap.common.proto;

public final class AdsZoneProto {
    private AdsZoneProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface AdsZoneMessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:io.union.wap.common.proto.AdsZoneMessage)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>uint64 zoneid = 1;</code>
         */
        long getZoneid();

        /**
         * <code>uint64 uid = 2;</code>
         */
        long getUid();

        /**
         * <code>uint32 zstatus = 3;</code>
         */
        int getZstatus();

        /**
         * <code>string zonename = 4;</code>
         */
        java.lang.String getZonename();

        /**
         * <code>string zonename = 4;</code>
         */
        com.google.protobuf.ByteString
        getZonenameBytes();

        /**
         * <code>uint32 paytype = 5;</code>
         */
        int getPaytype();

        /**
         * <code>uint32 viewtype = 6;</code>
         */
        int getViewtype();

        /**
         * <code>string viewadids = 7;</code>
         */
        java.lang.String getViewadids();

        /**
         * <code>string viewadids = 7;</code>
         */
        com.google.protobuf.ByteString
        getViewadidsBytes();

        /**
         * <code>uint32 width = 8;</code>
         */
        int getWidth();

        /**
         * <code>uint32 height = 9;</code>
         */
        int getHeight();

        /**
         * <code>string hcontrol = 10;</code>
         */
        java.lang.String getHcontrol();

        /**
         * <code>string hcontrol = 10;</code>
         */
        com.google.protobuf.ByteString
        getHcontrolBytes();

        /**
         * <code>uint64 add_time = 11;</code>
         */
        long getAddTime();

        /**
         * <code>string jdomain = 12;</code>
         */
        java.lang.String getJdomain();

        /**
         * <code>string jdomain = 12;</code>
         */
        com.google.protobuf.ByteString
        getJdomainBytes();

        /**
         * <code>string idomain = 13;</code>
         */
        java.lang.String getIdomain();

        /**
         * <code>string idomain = 13;</code>
         */
        com.google.protobuf.ByteString
        getIdomainBytes();

        /**
         * <code>string description = 14;</code>
         */
        java.lang.String getDescription();

        /**
         * <code>string description = 14;</code>
         */
        com.google.protobuf.ByteString
        getDescriptionBytes();

        /**
         * <code>string viewname = 15;</code>
         */
        java.lang.String getViewname();

        /**
         * <code>string viewname = 15;</code>
         */
        com.google.protobuf.ByteString
        getViewnameBytes();
    }

    /**
     * Protobuf type {@code io.union.wap.common.proto.AdsZoneMessage}
     */
    public static final class AdsZoneMessage extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:io.union.wap.common.proto.AdsZoneMessage)
            AdsZoneMessageOrBuilder {
        // Use AdsZoneMessage.newBuilder() to construct.
        private AdsZoneMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private AdsZoneMessage() {
            zoneid_ = 0L;
            uid_ = 0L;
            zstatus_ = 0;
            zonename_ = "";
            paytype_ = 0;
            viewtype_ = 0;
            viewadids_ = "";
            width_ = 0;
            height_ = 0;
            hcontrol_ = "";
            addTime_ = 0L;
            jdomain_ = "";
            idomain_ = "";
            description_ = "";
            viewname_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private AdsZoneMessage(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            zoneid_ = input.readUInt64();
                            break;
                        }
                        case 16: {

                            uid_ = input.readUInt64();
                            break;
                        }
                        case 24: {

                            zstatus_ = input.readUInt32();
                            break;
                        }
                        case 34: {
                            java.lang.String s = input.readStringRequireUtf8();

                            zonename_ = s;
                            break;
                        }
                        case 40: {

                            paytype_ = input.readUInt32();
                            break;
                        }
                        case 48: {

                            viewtype_ = input.readUInt32();
                            break;
                        }
                        case 58: {
                            java.lang.String s = input.readStringRequireUtf8();

                            viewadids_ = s;
                            break;
                        }
                        case 64: {

                            width_ = input.readUInt32();
                            break;
                        }
                        case 72: {

                            height_ = input.readUInt32();
                            break;
                        }
                        case 82: {
                            java.lang.String s = input.readStringRequireUtf8();

                            hcontrol_ = s;
                            break;
                        }
                        case 88: {

                            addTime_ = input.readUInt64();
                            break;
                        }
                        case 98: {
                            java.lang.String s = input.readStringRequireUtf8();

                            jdomain_ = s;
                            break;
                        }
                        case 106: {
                            java.lang.String s = input.readStringRequireUtf8();

                            idomain_ = s;
                            break;
                        }
                        case 114: {
                            java.lang.String s = input.readStringRequireUtf8();

                            description_ = s;
                            break;
                        }
                        case 122: {
                            java.lang.String s = input.readStringRequireUtf8();

                            viewname_ = s;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return io.union.wap.common.proto.AdsZoneProto.internal_static_io_union_wap_common_proto_AdsZoneMessage_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return io.union.wap.common.proto.AdsZoneProto.internal_static_io_union_wap_common_proto_AdsZoneMessage_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage.class, io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage.Builder.class);
        }

        public static final int ZONEID_FIELD_NUMBER = 1;
        private long zoneid_;

        /**
         * <code>uint64 zoneid = 1;</code>
         */
        public long getZoneid() {
            return zoneid_;
        }

        public static final int UID_FIELD_NUMBER = 2;
        private long uid_;

        /**
         * <code>uint64 uid = 2;</code>
         */
        public long getUid() {
            return uid_;
        }

        public static final int ZSTATUS_FIELD_NUMBER = 3;
        private int zstatus_;

        /**
         * <code>uint32 zstatus = 3;</code>
         */
        public int getZstatus() {
            return zstatus_;
        }

        public static final int ZONENAME_FIELD_NUMBER = 4;
        private volatile java.lang.Object zonename_;

        /**
         * <code>string zonename = 4;</code>
         */
        public java.lang.String getZonename() {
            java.lang.Object ref = zonename_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                zonename_ = s;
                return s;
            }
        }

        /**
         * <code>string zonename = 4;</code>
         */
        public com.google.protobuf.ByteString
        getZonenameBytes() {
            java.lang.Object ref = zonename_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                zonename_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int PAYTYPE_FIELD_NUMBER = 5;
        private int paytype_;

        /**
         * <code>uint32 paytype = 5;</code>
         */
        public int getPaytype() {
            return paytype_;
        }

        public static final int VIEWTYPE_FIELD_NUMBER = 6;
        private int viewtype_;

        /**
         * <code>uint32 viewtype = 6;</code>
         */
        public int getViewtype() {
            return viewtype_;
        }

        public static final int VIEWADIDS_FIELD_NUMBER = 7;
        private volatile java.lang.Object viewadids_;

        /**
         * <code>string viewadids = 7;</code>
         */
        public java.lang.String getViewadids() {
            java.lang.Object ref = viewadids_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                viewadids_ = s;
                return s;
            }
        }

        /**
         * <code>string viewadids = 7;</code>
         */
        public com.google.protobuf.ByteString
        getViewadidsBytes() {
            java.lang.Object ref = viewadids_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                viewadids_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int WIDTH_FIELD_NUMBER = 8;
        private int width_;

        /**
         * <code>uint32 width = 8;</code>
         */
        public int getWidth() {
            return width_;
        }

        public static final int HEIGHT_FIELD_NUMBER = 9;
        private int height_;

        /**
         * <code>uint32 height = 9;</code>
         */
        public int getHeight() {
            return height_;
        }

        public static final int HCONTROL_FIELD_NUMBER = 10;
        private volatile java.lang.Object hcontrol_;

        /**
         * <code>string hcontrol = 10;</code>
         */
        public java.lang.String getHcontrol() {
            java.lang.Object ref = hcontrol_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                hcontrol_ = s;
                return s;
            }
        }

        /**
         * <code>string hcontrol = 10;</code>
         */
        public com.google.protobuf.ByteString
        getHcontrolBytes() {
            java.lang.Object ref = hcontrol_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                hcontrol_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int ADD_TIME_FIELD_NUMBER = 11;
        private long addTime_;

        /**
         * <code>uint64 add_time = 11;</code>
         */
        public long getAddTime() {
            return addTime_;
        }

        public static final int JDOMAIN_FIELD_NUMBER = 12;
        private volatile java.lang.Object jdomain_;

        /**
         * <code>string jdomain = 12;</code>
         */
        public java.lang.String getJdomain() {
            java.lang.Object ref = jdomain_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                jdomain_ = s;
                return s;
            }
        }

        /**
         * <code>string jdomain = 12;</code>
         */
        public com.google.protobuf.ByteString
        getJdomainBytes() {
            java.lang.Object ref = jdomain_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                jdomain_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int IDOMAIN_FIELD_NUMBER = 13;
        private volatile java.lang.Object idomain_;

        /**
         * <code>string idomain = 13;</code>
         */
        public java.lang.String getIdomain() {
            java.lang.Object ref = idomain_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                idomain_ = s;
                return s;
            }
        }

        /**
         * <code>string idomain = 13;</code>
         */
        public com.google.protobuf.ByteString
        getIdomainBytes() {
            java.lang.Object ref = idomain_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                idomain_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int DESCRIPTION_FIELD_NUMBER = 14;
        private volatile java.lang.Object description_;

        /**
         * <code>string description = 14;</code>
         */
        public java.lang.String getDescription() {
            java.lang.Object ref = description_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                description_ = s;
                return s;
            }
        }

        /**
         * <code>string description = 14;</code>
         */
        public com.google.protobuf.ByteString
        getDescriptionBytes() {
            java.lang.Object ref = description_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                description_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int VIEWNAME_FIELD_NUMBER = 15;
        private volatile java.lang.Object viewname_;

        /**
         * <code>string viewname = 15;</code>
         */
        public java.lang.String getViewname() {
            java.lang.Object ref = viewname_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                viewname_ = s;
                return s;
            }
        }

        /**
         * <code>string viewname = 15;</code>
         */
        public com.google.protobuf.ByteString
        getViewnameBytes() {
            java.lang.Object ref = viewname_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                viewname_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (zoneid_ != 0L) {
                output.writeUInt64(1, zoneid_);
            }
            if (uid_ != 0L) {
                output.writeUInt64(2, uid_);
            }
            if (zstatus_ != 0) {
                output.writeUInt32(3, zstatus_);
            }
            if (!getZonenameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, zonename_);
            }
            if (paytype_ != 0) {
                output.writeUInt32(5, paytype_);
            }
            if (viewtype_ != 0) {
                output.writeUInt32(6, viewtype_);
            }
            if (!getViewadidsBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 7, viewadids_);
            }
            if (width_ != 0) {
                output.writeUInt32(8, width_);
            }
            if (height_ != 0) {
                output.writeUInt32(9, height_);
            }
            if (!getHcontrolBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 10, hcontrol_);
            }
            if (addTime_ != 0L) {
                output.writeUInt64(11, addTime_);
            }
            if (!getJdomainBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 12, jdomain_);
            }
            if (!getIdomainBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 13, idomain_);
            }
            if (!getDescriptionBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 14, description_);
            }
            if (!getViewnameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 15, viewname_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (zoneid_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(1, zoneid_);
            }
            if (uid_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(2, uid_);
            }
            if (zstatus_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(3, zstatus_);
            }
            if (!getZonenameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, zonename_);
            }
            if (paytype_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(5, paytype_);
            }
            if (viewtype_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(6, viewtype_);
            }
            if (!getViewadidsBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, viewadids_);
            }
            if (width_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(8, width_);
            }
            if (height_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(9, height_);
            }
            if (!getHcontrolBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, hcontrol_);
            }
            if (addTime_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(11, addTime_);
            }
            if (!getJdomainBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, jdomain_);
            }
            if (!getIdomainBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, idomain_);
            }
            if (!getDescriptionBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, description_);
            }
            if (!getViewnameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, viewname_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage)) {
                return super.equals(obj);
            }
            io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage other = (io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage) obj;

            boolean result = true;
            result = result && (getZoneid()
                    == other.getZoneid());
            result = result && (getUid()
                    == other.getUid());
            result = result && (getZstatus()
                    == other.getZstatus());
            result = result && getZonename()
                    .equals(other.getZonename());
            result = result && (getPaytype()
                    == other.getPaytype());
            result = result && (getViewtype()
                    == other.getViewtype());
            result = result && getViewadids()
                    .equals(other.getViewadids());
            result = result && (getWidth()
                    == other.getWidth());
            result = result && (getHeight()
                    == other.getHeight());
            result = result && getHcontrol()
                    .equals(other.getHcontrol());
            result = result && (getAddTime()
                    == other.getAddTime());
            result = result && getJdomain()
                    .equals(other.getJdomain());
            result = result && getIdomain()
                    .equals(other.getIdomain());
            result = result && getDescription()
                    .equals(other.getDescription());
            result = result && getViewname()
                    .equals(other.getViewname());
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ZONEID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getZoneid());
            hash = (37 * hash) + UID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getUid());
            hash = (37 * hash) + ZSTATUS_FIELD_NUMBER;
            hash = (53 * hash) + getZstatus();
            hash = (37 * hash) + ZONENAME_FIELD_NUMBER;
            hash = (53 * hash) + getZonename().hashCode();
            hash = (37 * hash) + PAYTYPE_FIELD_NUMBER;
            hash = (53 * hash) + getPaytype();
            hash = (37 * hash) + VIEWTYPE_FIELD_NUMBER;
            hash = (53 * hash) + getViewtype();
            hash = (37 * hash) + VIEWADIDS_FIELD_NUMBER;
            hash = (53 * hash) + getViewadids().hashCode();
            hash = (37 * hash) + WIDTH_FIELD_NUMBER;
            hash = (53 * hash) + getWidth();
            hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
            hash = (53 * hash) + getHeight();
            hash = (37 * hash) + HCONTROL_FIELD_NUMBER;
            hash = (53 * hash) + getHcontrol().hashCode();
            hash = (37 * hash) + ADD_TIME_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getAddTime());
            hash = (37 * hash) + JDOMAIN_FIELD_NUMBER;
            hash = (53 * hash) + getJdomain().hashCode();
            hash = (37 * hash) + IDOMAIN_FIELD_NUMBER;
            hash = (53 * hash) + getIdomain().hashCode();
            hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
            hash = (53 * hash) + getDescription().hashCode();
            hash = (37 * hash) + VIEWNAME_FIELD_NUMBER;
            hash = (53 * hash) + getViewname().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code io.union.wap.common.proto.AdsZoneMessage}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:io.union.wap.common.proto.AdsZoneMessage)
                io.union.wap.common.proto.AdsZoneProto.AdsZoneMessageOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return io.union.wap.common.proto.AdsZoneProto.internal_static_io_union_wap_common_proto_AdsZoneMessage_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return io.union.wap.common.proto.AdsZoneProto.internal_static_io_union_wap_common_proto_AdsZoneMessage_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage.class, io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage.Builder.class);
            }

            // Construct using io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                zoneid_ = 0L;

                uid_ = 0L;

                zstatus_ = 0;

                zonename_ = "";

                paytype_ = 0;

                viewtype_ = 0;

                viewadids_ = "";

                width_ = 0;

                height_ = 0;

                hcontrol_ = "";

                addTime_ = 0L;

                jdomain_ = "";

                idomain_ = "";

                description_ = "";

                viewname_ = "";

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return io.union.wap.common.proto.AdsZoneProto.internal_static_io_union_wap_common_proto_AdsZoneMessage_descriptor;
            }

            public io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage getDefaultInstanceForType() {
                return io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage.getDefaultInstance();
            }

            public io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage build() {
                io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage buildPartial() {
                io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage result = new io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage(this);
                result.zoneid_ = zoneid_;
                result.uid_ = uid_;
                result.zstatus_ = zstatus_;
                result.zonename_ = zonename_;
                result.paytype_ = paytype_;
                result.viewtype_ = viewtype_;
                result.viewadids_ = viewadids_;
                result.width_ = width_;
                result.height_ = height_;
                result.hcontrol_ = hcontrol_;
                result.addTime_ = addTime_;
                result.jdomain_ = jdomain_;
                result.idomain_ = idomain_;
                result.description_ = description_;
                result.viewname_ = viewname_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage) {
                    return mergeFrom((io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage other) {
                if (other == io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage.getDefaultInstance()) return this;
                if (other.getZoneid() != 0L) {
                    setZoneid(other.getZoneid());
                }
                if (other.getUid() != 0L) {
                    setUid(other.getUid());
                }
                if (other.getZstatus() != 0) {
                    setZstatus(other.getZstatus());
                }
                if (!other.getZonename().isEmpty()) {
                    zonename_ = other.zonename_;
                    onChanged();
                }
                if (other.getPaytype() != 0) {
                    setPaytype(other.getPaytype());
                }
                if (other.getViewtype() != 0) {
                    setViewtype(other.getViewtype());
                }
                if (!other.getViewadids().isEmpty()) {
                    viewadids_ = other.viewadids_;
                    onChanged();
                }
                if (other.getWidth() != 0) {
                    setWidth(other.getWidth());
                }
                if (other.getHeight() != 0) {
                    setHeight(other.getHeight());
                }
                if (!other.getHcontrol().isEmpty()) {
                    hcontrol_ = other.hcontrol_;
                    onChanged();
                }
                if (other.getAddTime() != 0L) {
                    setAddTime(other.getAddTime());
                }
                if (!other.getJdomain().isEmpty()) {
                    jdomain_ = other.jdomain_;
                    onChanged();
                }
                if (!other.getIdomain().isEmpty()) {
                    idomain_ = other.idomain_;
                    onChanged();
                }
                if (!other.getDescription().isEmpty()) {
                    description_ = other.description_;
                    onChanged();
                }
                if (!other.getViewname().isEmpty()) {
                    viewname_ = other.viewname_;
                    onChanged();
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private long zoneid_;

            /**
             * <code>uint64 zoneid = 1;</code>
             */
            public long getZoneid() {
                return zoneid_;
            }

            /**
             * <code>uint64 zoneid = 1;</code>
             */
            public Builder setZoneid(long value) {

                zoneid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 zoneid = 1;</code>
             */
            public Builder clearZoneid() {

                zoneid_ = 0L;
                onChanged();
                return this;
            }

            private long uid_;

            /**
             * <code>uint64 uid = 2;</code>
             */
            public long getUid() {
                return uid_;
            }

            /**
             * <code>uint64 uid = 2;</code>
             */
            public Builder setUid(long value) {

                uid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 uid = 2;</code>
             */
            public Builder clearUid() {

                uid_ = 0L;
                onChanged();
                return this;
            }

            private int zstatus_;

            /**
             * <code>uint32 zstatus = 3;</code>
             */
            public int getZstatus() {
                return zstatus_;
            }

            /**
             * <code>uint32 zstatus = 3;</code>
             */
            public Builder setZstatus(int value) {

                zstatus_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint32 zstatus = 3;</code>
             */
            public Builder clearZstatus() {

                zstatus_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object zonename_ = "";

            /**
             * <code>string zonename = 4;</code>
             */
            public java.lang.String getZonename() {
                java.lang.Object ref = zonename_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    zonename_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string zonename = 4;</code>
             */
            public com.google.protobuf.ByteString
            getZonenameBytes() {
                java.lang.Object ref = zonename_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    zonename_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string zonename = 4;</code>
             */
            public Builder setZonename(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                zonename_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string zonename = 4;</code>
             */
            public Builder clearZonename() {

                zonename_ = getDefaultInstance().getZonename();
                onChanged();
                return this;
            }

            /**
             * <code>string zonename = 4;</code>
             */
            public Builder setZonenameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                zonename_ = value;
                onChanged();
                return this;
            }

            private int paytype_;

            /**
             * <code>uint32 paytype = 5;</code>
             */
            public int getPaytype() {
                return paytype_;
            }

            /**
             * <code>uint32 paytype = 5;</code>
             */
            public Builder setPaytype(int value) {

                paytype_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint32 paytype = 5;</code>
             */
            public Builder clearPaytype() {

                paytype_ = 0;
                onChanged();
                return this;
            }

            private int viewtype_;

            /**
             * <code>uint32 viewtype = 6;</code>
             */
            public int getViewtype() {
                return viewtype_;
            }

            /**
             * <code>uint32 viewtype = 6;</code>
             */
            public Builder setViewtype(int value) {

                viewtype_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint32 viewtype = 6;</code>
             */
            public Builder clearViewtype() {

                viewtype_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object viewadids_ = "";

            /**
             * <code>string viewadids = 7;</code>
             */
            public java.lang.String getViewadids() {
                java.lang.Object ref = viewadids_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    viewadids_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string viewadids = 7;</code>
             */
            public com.google.protobuf.ByteString
            getViewadidsBytes() {
                java.lang.Object ref = viewadids_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    viewadids_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string viewadids = 7;</code>
             */
            public Builder setViewadids(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                viewadids_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string viewadids = 7;</code>
             */
            public Builder clearViewadids() {

                viewadids_ = getDefaultInstance().getViewadids();
                onChanged();
                return this;
            }

            /**
             * <code>string viewadids = 7;</code>
             */
            public Builder setViewadidsBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                viewadids_ = value;
                onChanged();
                return this;
            }

            private int width_;

            /**
             * <code>uint32 width = 8;</code>
             */
            public int getWidth() {
                return width_;
            }

            /**
             * <code>uint32 width = 8;</code>
             */
            public Builder setWidth(int value) {

                width_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint32 width = 8;</code>
             */
            public Builder clearWidth() {

                width_ = 0;
                onChanged();
                return this;
            }

            private int height_;

            /**
             * <code>uint32 height = 9;</code>
             */
            public int getHeight() {
                return height_;
            }

            /**
             * <code>uint32 height = 9;</code>
             */
            public Builder setHeight(int value) {

                height_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint32 height = 9;</code>
             */
            public Builder clearHeight() {

                height_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object hcontrol_ = "";

            /**
             * <code>string hcontrol = 10;</code>
             */
            public java.lang.String getHcontrol() {
                java.lang.Object ref = hcontrol_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    hcontrol_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string hcontrol = 10;</code>
             */
            public com.google.protobuf.ByteString
            getHcontrolBytes() {
                java.lang.Object ref = hcontrol_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    hcontrol_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string hcontrol = 10;</code>
             */
            public Builder setHcontrol(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                hcontrol_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string hcontrol = 10;</code>
             */
            public Builder clearHcontrol() {

                hcontrol_ = getDefaultInstance().getHcontrol();
                onChanged();
                return this;
            }

            /**
             * <code>string hcontrol = 10;</code>
             */
            public Builder setHcontrolBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                hcontrol_ = value;
                onChanged();
                return this;
            }

            private long addTime_;

            /**
             * <code>uint64 add_time = 11;</code>
             */
            public long getAddTime() {
                return addTime_;
            }

            /**
             * <code>uint64 add_time = 11;</code>
             */
            public Builder setAddTime(long value) {

                addTime_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 add_time = 11;</code>
             */
            public Builder clearAddTime() {

                addTime_ = 0L;
                onChanged();
                return this;
            }

            private java.lang.Object jdomain_ = "";

            /**
             * <code>string jdomain = 12;</code>
             */
            public java.lang.String getJdomain() {
                java.lang.Object ref = jdomain_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    jdomain_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string jdomain = 12;</code>
             */
            public com.google.protobuf.ByteString
            getJdomainBytes() {
                java.lang.Object ref = jdomain_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    jdomain_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string jdomain = 12;</code>
             */
            public Builder setJdomain(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                jdomain_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string jdomain = 12;</code>
             */
            public Builder clearJdomain() {

                jdomain_ = getDefaultInstance().getJdomain();
                onChanged();
                return this;
            }

            /**
             * <code>string jdomain = 12;</code>
             */
            public Builder setJdomainBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                jdomain_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object idomain_ = "";

            /**
             * <code>string idomain = 13;</code>
             */
            public java.lang.String getIdomain() {
                java.lang.Object ref = idomain_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    idomain_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string idomain = 13;</code>
             */
            public com.google.protobuf.ByteString
            getIdomainBytes() {
                java.lang.Object ref = idomain_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    idomain_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string idomain = 13;</code>
             */
            public Builder setIdomain(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                idomain_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string idomain = 13;</code>
             */
            public Builder clearIdomain() {

                idomain_ = getDefaultInstance().getIdomain();
                onChanged();
                return this;
            }

            /**
             * <code>string idomain = 13;</code>
             */
            public Builder setIdomainBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                idomain_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object description_ = "";

            /**
             * <code>string description = 14;</code>
             */
            public java.lang.String getDescription() {
                java.lang.Object ref = description_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    description_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string description = 14;</code>
             */
            public com.google.protobuf.ByteString
            getDescriptionBytes() {
                java.lang.Object ref = description_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    description_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string description = 14;</code>
             */
            public Builder setDescription(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                description_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string description = 14;</code>
             */
            public Builder clearDescription() {

                description_ = getDefaultInstance().getDescription();
                onChanged();
                return this;
            }

            /**
             * <code>string description = 14;</code>
             */
            public Builder setDescriptionBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                description_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object viewname_ = "";

            /**
             * <code>string viewname = 15;</code>
             */
            public java.lang.String getViewname() {
                java.lang.Object ref = viewname_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    viewname_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string viewname = 15;</code>
             */
            public com.google.protobuf.ByteString
            getViewnameBytes() {
                java.lang.Object ref = viewname_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    viewname_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string viewname = 15;</code>
             */
            public Builder setViewname(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                viewname_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string viewname = 15;</code>
             */
            public Builder clearViewname() {

                viewname_ = getDefaultInstance().getViewname();
                onChanged();
                return this;
            }

            /**
             * <code>string viewname = 15;</code>
             */
            public Builder setViewnameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                viewname_ = value;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:io.union.wap.common.proto.AdsZoneMessage)
        }

        // @@protoc_insertion_point(class_scope:io.union.wap.common.proto.AdsZoneMessage)
        private static final io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage();
        }

        public static io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<AdsZoneMessage>
                PARSER = new com.google.protobuf.AbstractParser<AdsZoneMessage>() {
            public AdsZoneMessage parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new AdsZoneMessage(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<AdsZoneMessage> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<AdsZoneMessage> getParserForType() {
            return PARSER;
        }

        public io.union.wap.common.proto.AdsZoneProto.AdsZoneMessage getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_io_union_wap_common_proto_AdsZoneMessage_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_io_union_wap_common_proto_AdsZoneMessage_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\rAdsZone.proto\022\031io.union.wap.common.pro" +
                        "to\"\222\002\n\016AdsZoneMessage\022\016\n\006zoneid\030\001 \001(\004\022\013\n" +
                        "\003uid\030\002 \001(\004\022\017\n\007zstatus\030\003 \001(\r\022\020\n\010zonename\030" +
                        "\004 \001(\t\022\017\n\007paytype\030\005 \001(\r\022\020\n\010viewtype\030\006 \001(\r" +
                        "\022\021\n\tviewadids\030\007 \001(\t\022\r\n\005width\030\010 \001(\r\022\016\n\006he" +
                        "ight\030\t \001(\r\022\020\n\010hcontrol\030\n \001(\t\022\020\n\010add_time" +
                        "\030\013 \001(\004\022\017\n\007jdomain\030\014 \001(\t\022\017\n\007idomain\030\r \001(\t" +
                        "\022\023\n\013description\030\016 \001(\t\022\020\n\010viewname\030\017 \001(\tB" +
                        ")\n\031io.union.wap.common.protoB\014AdsZonePro" +
                        "tob\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_io_union_wap_common_proto_AdsZoneMessage_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_io_union_wap_common_proto_AdsZoneMessage_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_io_union_wap_common_proto_AdsZoneMessage_descriptor,
                new java.lang.String[]{"Zoneid", "Uid", "Zstatus", "Zonename", "Paytype", "Viewtype", "Viewadids", "Width", "Height", "Hcontrol", "AddTime", "Jdomain", "Idomain", "Description", "Viewname",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
