// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AdsArticle.proto

package io.union.admin.common.proto;

public final class AdsArticleProto {
    private AdsArticleProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface AdsArticleMessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:io.union.wap.common.proto.AdsArticleMessage)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>uint64 id = 1;</code>
         */
        long getId();

        /**
         * <code>string title = 2;</code>
         */
        java.lang.String getTitle();

        /**
         * <code>string title = 2;</code>
         */
        com.google.protobuf.ByteString
        getTitleBytes();

        /**
         * <code>string summary = 3;</code>
         */
        java.lang.String getSummary();

        /**
         * <code>string summary = 3;</code>
         */
        com.google.protobuf.ByteString
        getSummaryBytes();

        /**
         * <code>string content = 4;</code>
         */
        java.lang.String getContent();

        /**
         * <code>string content = 4;</code>
         */
        com.google.protobuf.ByteString
        getContentBytes();

        /**
         * <code>string atop = 5;</code>
         */
        java.lang.String getAtop();

        /**
         * <code>string atop = 5;</code>
         */
        com.google.protobuf.ByteString
        getAtopBytes();

        /**
         * <code>uint32 asort = 6;</code>
         */
        int getAsort();

        /**
         * <code>string astatus = 7;</code>
         */
        java.lang.String getAstatus();

        /**
         * <code>string astatus = 7;</code>
         */
        com.google.protobuf.ByteString
        getAstatusBytes();

        /**
         * <code>uint64 add_time = 8;</code>
         */
        long getAddTime();

        /**
         * <code>uint64 begin_time = 9;</code>
         */
        long getBeginTime();

        /**
         * <code>uint64 end_time = 10;</code>
         */
        long getEndTime();
    }

    /**
     * Protobuf type {@code io.union.wap.common.proto.AdsArticleMessage}
     */
    public static final class AdsArticleMessage extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:io.union.wap.common.proto.AdsArticleMessage)
            AdsArticleMessageOrBuilder {
        // Use AdsArticleMessage.newBuilder() to construct.
        private AdsArticleMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private AdsArticleMessage() {
            id_ = 0L;
            title_ = "";
            summary_ = "";
            content_ = "";
            atop_ = "";
            asort_ = 0;
            astatus_ = "";
            addTime_ = 0L;
            beginTime_ = 0L;
            endTime_ = 0L;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private AdsArticleMessage(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            id_ = input.readUInt64();
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            title_ = s;
                            break;
                        }
                        case 26: {
                            java.lang.String s = input.readStringRequireUtf8();

                            summary_ = s;
                            break;
                        }
                        case 34: {
                            java.lang.String s = input.readStringRequireUtf8();

                            content_ = s;
                            break;
                        }
                        case 42: {
                            java.lang.String s = input.readStringRequireUtf8();

                            atop_ = s;
                            break;
                        }
                        case 48: {

                            asort_ = input.readUInt32();
                            break;
                        }
                        case 58: {
                            java.lang.String s = input.readStringRequireUtf8();

                            astatus_ = s;
                            break;
                        }
                        case 64: {

                            addTime_ = input.readUInt64();
                            break;
                        }
                        case 72: {

                            beginTime_ = input.readUInt64();
                            break;
                        }
                        case 80: {

                            endTime_ = input.readUInt64();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return io.union.admin.common.proto.AdsArticleProto.internal_static_io_union_wap_common_proto_AdsArticleMessage_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return io.union.admin.common.proto.AdsArticleProto.internal_static_io_union_wap_common_proto_AdsArticleMessage_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage.class, io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage.Builder.class);
        }

        public static final int ID_FIELD_NUMBER = 1;
        private long id_;

        /**
         * <code>uint64 id = 1;</code>
         */
        public long getId() {
            return id_;
        }

        public static final int TITLE_FIELD_NUMBER = 2;
        private volatile java.lang.Object title_;

        /**
         * <code>string title = 2;</code>
         */
        public java.lang.String getTitle() {
            java.lang.Object ref = title_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                title_ = s;
                return s;
            }
        }

        /**
         * <code>string title = 2;</code>
         */
        public com.google.protobuf.ByteString
        getTitleBytes() {
            java.lang.Object ref = title_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                title_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int SUMMARY_FIELD_NUMBER = 3;
        private volatile java.lang.Object summary_;

        /**
         * <code>string summary = 3;</code>
         */
        public java.lang.String getSummary() {
            java.lang.Object ref = summary_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                summary_ = s;
                return s;
            }
        }

        /**
         * <code>string summary = 3;</code>
         */
        public com.google.protobuf.ByteString
        getSummaryBytes() {
            java.lang.Object ref = summary_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                summary_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int CONTENT_FIELD_NUMBER = 4;
        private volatile java.lang.Object content_;

        /**
         * <code>string content = 4;</code>
         */
        public java.lang.String getContent() {
            java.lang.Object ref = content_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                content_ = s;
                return s;
            }
        }

        /**
         * <code>string content = 4;</code>
         */
        public com.google.protobuf.ByteString
        getContentBytes() {
            java.lang.Object ref = content_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                content_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int ATOP_FIELD_NUMBER = 5;
        private volatile java.lang.Object atop_;

        /**
         * <code>string atop = 5;</code>
         */
        public java.lang.String getAtop() {
            java.lang.Object ref = atop_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                atop_ = s;
                return s;
            }
        }

        /**
         * <code>string atop = 5;</code>
         */
        public com.google.protobuf.ByteString
        getAtopBytes() {
            java.lang.Object ref = atop_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                atop_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int ASORT_FIELD_NUMBER = 6;
        private int asort_;

        /**
         * <code>uint32 asort = 6;</code>
         */
        public int getAsort() {
            return asort_;
        }

        public static final int ASTATUS_FIELD_NUMBER = 7;
        private volatile java.lang.Object astatus_;

        /**
         * <code>string astatus = 7;</code>
         */
        public java.lang.String getAstatus() {
            java.lang.Object ref = astatus_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                astatus_ = s;
                return s;
            }
        }

        /**
         * <code>string astatus = 7;</code>
         */
        public com.google.protobuf.ByteString
        getAstatusBytes() {
            java.lang.Object ref = astatus_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                astatus_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int ADD_TIME_FIELD_NUMBER = 8;
        private long addTime_;

        /**
         * <code>uint64 add_time = 8;</code>
         */
        public long getAddTime() {
            return addTime_;
        }

        public static final int BEGIN_TIME_FIELD_NUMBER = 9;
        private long beginTime_;

        /**
         * <code>uint64 begin_time = 9;</code>
         */
        public long getBeginTime() {
            return beginTime_;
        }

        public static final int END_TIME_FIELD_NUMBER = 10;
        private long endTime_;

        /**
         * <code>uint64 end_time = 10;</code>
         */
        public long getEndTime() {
            return endTime_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (id_ != 0L) {
                output.writeUInt64(1, id_);
            }
            if (!getTitleBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
            }
            if (!getSummaryBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, summary_);
            }
            if (!getContentBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, content_);
            }
            if (!getAtopBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 5, atop_);
            }
            if (asort_ != 0) {
                output.writeUInt32(6, asort_);
            }
            if (!getAstatusBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 7, astatus_);
            }
            if (addTime_ != 0L) {
                output.writeUInt64(8, addTime_);
            }
            if (beginTime_ != 0L) {
                output.writeUInt64(9, beginTime_);
            }
            if (endTime_ != 0L) {
                output.writeUInt64(10, endTime_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (id_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(1, id_);
            }
            if (!getTitleBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
            }
            if (!getSummaryBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, summary_);
            }
            if (!getContentBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, content_);
            }
            if (!getAtopBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, atop_);
            }
            if (asort_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(6, asort_);
            }
            if (!getAstatusBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, astatus_);
            }
            if (addTime_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(8, addTime_);
            }
            if (beginTime_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(9, beginTime_);
            }
            if (endTime_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(10, endTime_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage)) {
                return super.equals(obj);
            }
            io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage other = (io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage) obj;

            boolean result = true;
            result = result && (getId()
                    == other.getId());
            result = result && getTitle()
                    .equals(other.getTitle());
            result = result && getSummary()
                    .equals(other.getSummary());
            result = result && getContent()
                    .equals(other.getContent());
            result = result && getAtop()
                    .equals(other.getAtop());
            result = result && (getAsort()
                    == other.getAsort());
            result = result && getAstatus()
                    .equals(other.getAstatus());
            result = result && (getAddTime()
                    == other.getAddTime());
            result = result && (getBeginTime()
                    == other.getBeginTime());
            result = result && (getEndTime()
                    == other.getEndTime());
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getId());
            hash = (37 * hash) + TITLE_FIELD_NUMBER;
            hash = (53 * hash) + getTitle().hashCode();
            hash = (37 * hash) + SUMMARY_FIELD_NUMBER;
            hash = (53 * hash) + getSummary().hashCode();
            hash = (37 * hash) + CONTENT_FIELD_NUMBER;
            hash = (53 * hash) + getContent().hashCode();
            hash = (37 * hash) + ATOP_FIELD_NUMBER;
            hash = (53 * hash) + getAtop().hashCode();
            hash = (37 * hash) + ASORT_FIELD_NUMBER;
            hash = (53 * hash) + getAsort();
            hash = (37 * hash) + ASTATUS_FIELD_NUMBER;
            hash = (53 * hash) + getAstatus().hashCode();
            hash = (37 * hash) + ADD_TIME_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getAddTime());
            hash = (37 * hash) + BEGIN_TIME_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getBeginTime());
            hash = (37 * hash) + END_TIME_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getEndTime());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code io.union.wap.common.proto.AdsArticleMessage}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:io.union.wap.common.proto.AdsArticleMessage)
                io.union.admin.common.proto.AdsArticleProto.AdsArticleMessageOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return io.union.admin.common.proto.AdsArticleProto.internal_static_io_union_wap_common_proto_AdsArticleMessage_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return io.union.admin.common.proto.AdsArticleProto.internal_static_io_union_wap_common_proto_AdsArticleMessage_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage.class, io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage.Builder.class);
            }

            // Construct using io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                id_ = 0L;

                title_ = "";

                summary_ = "";

                content_ = "";

                atop_ = "";

                asort_ = 0;

                astatus_ = "";

                addTime_ = 0L;

                beginTime_ = 0L;

                endTime_ = 0L;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return io.union.admin.common.proto.AdsArticleProto.internal_static_io_union_wap_common_proto_AdsArticleMessage_descriptor;
            }

            public io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage getDefaultInstanceForType() {
                return io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage.getDefaultInstance();
            }

            public io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage build() {
                io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage buildPartial() {
                io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage result = new io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage(this);
                result.id_ = id_;
                result.title_ = title_;
                result.summary_ = summary_;
                result.content_ = content_;
                result.atop_ = atop_;
                result.asort_ = asort_;
                result.astatus_ = astatus_;
                result.addTime_ = addTime_;
                result.beginTime_ = beginTime_;
                result.endTime_ = endTime_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage) {
                    return mergeFrom((io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage other) {
                if (other == io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage.getDefaultInstance())
                    return this;
                if (other.getId() != 0L) {
                    setId(other.getId());
                }
                if (!other.getTitle().isEmpty()) {
                    title_ = other.title_;
                    onChanged();
                }
                if (!other.getSummary().isEmpty()) {
                    summary_ = other.summary_;
                    onChanged();
                }
                if (!other.getContent().isEmpty()) {
                    content_ = other.content_;
                    onChanged();
                }
                if (!other.getAtop().isEmpty()) {
                    atop_ = other.atop_;
                    onChanged();
                }
                if (other.getAsort() != 0) {
                    setAsort(other.getAsort());
                }
                if (!other.getAstatus().isEmpty()) {
                    astatus_ = other.astatus_;
                    onChanged();
                }
                if (other.getAddTime() != 0L) {
                    setAddTime(other.getAddTime());
                }
                if (other.getBeginTime() != 0L) {
                    setBeginTime(other.getBeginTime());
                }
                if (other.getEndTime() != 0L) {
                    setEndTime(other.getEndTime());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private long id_;

            /**
             * <code>uint64 id = 1;</code>
             */
            public long getId() {
                return id_;
            }

            /**
             * <code>uint64 id = 1;</code>
             */
            public Builder setId(long value) {

                id_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 id = 1;</code>
             */
            public Builder clearId() {

                id_ = 0L;
                onChanged();
                return this;
            }

            private java.lang.Object title_ = "";

            /**
             * <code>string title = 2;</code>
             */
            public java.lang.String getTitle() {
                java.lang.Object ref = title_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    title_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string title = 2;</code>
             */
            public com.google.protobuf.ByteString
            getTitleBytes() {
                java.lang.Object ref = title_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    title_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string title = 2;</code>
             */
            public Builder setTitle(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                title_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string title = 2;</code>
             */
            public Builder clearTitle() {

                title_ = getDefaultInstance().getTitle();
                onChanged();
                return this;
            }

            /**
             * <code>string title = 2;</code>
             */
            public Builder setTitleBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                title_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object summary_ = "";

            /**
             * <code>string summary = 3;</code>
             */
            public java.lang.String getSummary() {
                java.lang.Object ref = summary_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    summary_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string summary = 3;</code>
             */
            public com.google.protobuf.ByteString
            getSummaryBytes() {
                java.lang.Object ref = summary_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    summary_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string summary = 3;</code>
             */
            public Builder setSummary(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                summary_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string summary = 3;</code>
             */
            public Builder clearSummary() {

                summary_ = getDefaultInstance().getSummary();
                onChanged();
                return this;
            }

            /**
             * <code>string summary = 3;</code>
             */
            public Builder setSummaryBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                summary_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object content_ = "";

            /**
             * <code>string content = 4;</code>
             */
            public java.lang.String getContent() {
                java.lang.Object ref = content_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    content_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string content = 4;</code>
             */
            public com.google.protobuf.ByteString
            getContentBytes() {
                java.lang.Object ref = content_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    content_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string content = 4;</code>
             */
            public Builder setContent(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                content_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string content = 4;</code>
             */
            public Builder clearContent() {

                content_ = getDefaultInstance().getContent();
                onChanged();
                return this;
            }

            /**
             * <code>string content = 4;</code>
             */
            public Builder setContentBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                content_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object atop_ = "";

            /**
             * <code>string atop = 5;</code>
             */
            public java.lang.String getAtop() {
                java.lang.Object ref = atop_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    atop_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string atop = 5;</code>
             */
            public com.google.protobuf.ByteString
            getAtopBytes() {
                java.lang.Object ref = atop_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    atop_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string atop = 5;</code>
             */
            public Builder setAtop(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                atop_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string atop = 5;</code>
             */
            public Builder clearAtop() {

                atop_ = getDefaultInstance().getAtop();
                onChanged();
                return this;
            }

            /**
             * <code>string atop = 5;</code>
             */
            public Builder setAtopBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                atop_ = value;
                onChanged();
                return this;
            }

            private int asort_;

            /**
             * <code>uint32 asort = 6;</code>
             */
            public int getAsort() {
                return asort_;
            }

            /**
             * <code>uint32 asort = 6;</code>
             */
            public Builder setAsort(int value) {

                asort_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint32 asort = 6;</code>
             */
            public Builder clearAsort() {

                asort_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object astatus_ = "";

            /**
             * <code>string astatus = 7;</code>
             */
            public java.lang.String getAstatus() {
                java.lang.Object ref = astatus_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    astatus_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string astatus = 7;</code>
             */
            public com.google.protobuf.ByteString
            getAstatusBytes() {
                java.lang.Object ref = astatus_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    astatus_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string astatus = 7;</code>
             */
            public Builder setAstatus(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                astatus_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string astatus = 7;</code>
             */
            public Builder clearAstatus() {

                astatus_ = getDefaultInstance().getAstatus();
                onChanged();
                return this;
            }

            /**
             * <code>string astatus = 7;</code>
             */
            public Builder setAstatusBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                astatus_ = value;
                onChanged();
                return this;
            }

            private long addTime_;

            /**
             * <code>uint64 add_time = 8;</code>
             */
            public long getAddTime() {
                return addTime_;
            }

            /**
             * <code>uint64 add_time = 8;</code>
             */
            public Builder setAddTime(long value) {

                addTime_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 add_time = 8;</code>
             */
            public Builder clearAddTime() {

                addTime_ = 0L;
                onChanged();
                return this;
            }

            private long beginTime_;

            /**
             * <code>uint64 begin_time = 9;</code>
             */
            public long getBeginTime() {
                return beginTime_;
            }

            /**
             * <code>uint64 begin_time = 9;</code>
             */
            public Builder setBeginTime(long value) {

                beginTime_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 begin_time = 9;</code>
             */
            public Builder clearBeginTime() {

                beginTime_ = 0L;
                onChanged();
                return this;
            }

            private long endTime_;

            /**
             * <code>uint64 end_time = 10;</code>
             */
            public long getEndTime() {
                return endTime_;
            }

            /**
             * <code>uint64 end_time = 10;</code>
             */
            public Builder setEndTime(long value) {

                endTime_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 end_time = 10;</code>
             */
            public Builder clearEndTime() {

                endTime_ = 0L;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:io.union.wap.common.proto.AdsArticleMessage)
        }

        // @@protoc_insertion_point(class_scope:io.union.wap.common.proto.AdsArticleMessage)
        private static final io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage();
        }

        public static io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<AdsArticleMessage>
                PARSER = new com.google.protobuf.AbstractParser<AdsArticleMessage>() {
            public AdsArticleMessage parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new AdsArticleMessage(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<AdsArticleMessage> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<AdsArticleMessage> getParserForType() {
            return PARSER;
        }

        public io.union.admin.common.proto.AdsArticleProto.AdsArticleMessage getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_io_union_wap_common_proto_AdsArticleMessage_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_io_union_wap_common_proto_AdsArticleMessage_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\020AdsArticle.proto\022\031io.union.wap.common." +
                        "proto\"\266\001\n\021AdsArticleMessage\022\n\n\002id\030\001 \001(\004\022" +
                        "\r\n\005title\030\002 \001(\t\022\017\n\007summary\030\003 \001(\t\022\017\n\007conte" +
                        "nt\030\004 \001(\t\022\014\n\004atop\030\005 \001(\t\022\r\n\005asort\030\006 \001(\r\022\017\n" +
                        "\007astatus\030\007 \001(\t\022\020\n\010add_time\030\010 \001(\004\022\022\n\nbegi" +
                        "n_time\030\t \001(\004\022\020\n\010end_time\030\n \001(\004B.\n\033io.uni" +
                        "on.admin.common.protoB\017AdsArticleProtob\006" +
                        "proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_io_union_wap_common_proto_AdsArticleMessage_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_io_union_wap_common_proto_AdsArticleMessage_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_io_union_wap_common_proto_AdsArticleMessage_descriptor,
                new java.lang.String[]{"Id", "Title", "Summary", "Content", "Atop", "Asort", "Astatus", "AddTime", "BeginTime", "EndTime",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
