// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LogBrowser.proto

package io.union.log.common.proto;

public final class LogBrowserProto {
    private LogBrowserProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface LogBrowserMessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:io.union.log.common.proto.LogBrowserMessage)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>uint64 id = 1;</code>
         */
        long getId();

        /**
         * <code>string brw_name = 2;</code>
         */
        java.lang.String getBrwName();

        /**
         * <code>string brw_name = 2;</code>
         */
        com.google.protobuf.ByteString
        getBrwNameBytes();

        /**
         * <code>string brw_version = 3;</code>
         */
        java.lang.String getBrwVersion();

        /**
         * <code>string brw_version = 3;</code>
         */
        com.google.protobuf.ByteString
        getBrwVersionBytes();

        /**
         * <code>string brw_plat = 4;</code>
         */
        java.lang.String getBrwPlat();

        /**
         * <code>string brw_plat = 4;</code>
         */
        com.google.protobuf.ByteString
        getBrwPlatBytes();

        /**
         * <code>uint64 brw_num = 5;</code>
         */
        long getBrwNum();

        /**
         * <code>uint64 uid = 6;</code>
         */
        long getUid();

        /**
         * <code>uint64 add_time = 7;</code>
         */
        long getAddTime();
    }

    /**
     * Protobuf type {@code io.union.log.common.proto.LogBrowserMessage}
     */
    public static final class LogBrowserMessage extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:io.union.log.common.proto.LogBrowserMessage)
            LogBrowserMessageOrBuilder {
        // Use LogBrowserMessage.newBuilder() to construct.
        private LogBrowserMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private LogBrowserMessage() {
            id_ = 0L;
            brwName_ = "";
            brwVersion_ = "";
            brwPlat_ = "";
            brwNum_ = 0L;
            uid_ = 0L;
            addTime_ = 0L;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private LogBrowserMessage(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            id_ = input.readUInt64();
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            brwName_ = s;
                            break;
                        }
                        case 26: {
                            java.lang.String s = input.readStringRequireUtf8();

                            brwVersion_ = s;
                            break;
                        }
                        case 34: {
                            java.lang.String s = input.readStringRequireUtf8();

                            brwPlat_ = s;
                            break;
                        }
                        case 40: {

                            brwNum_ = input.readUInt64();
                            break;
                        }
                        case 48: {

                            uid_ = input.readUInt64();
                            break;
                        }
                        case 56: {

                            addTime_ = input.readUInt64();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return io.union.log.common.proto.LogBrowserProto.internal_static_io_union_log_common_proto_LogBrowserMessage_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return io.union.log.common.proto.LogBrowserProto.internal_static_io_union_log_common_proto_LogBrowserMessage_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            io.union.log.common.proto.LogBrowserProto.LogBrowserMessage.class, io.union.log.common.proto.LogBrowserProto.LogBrowserMessage.Builder.class);
        }

        public static final int ID_FIELD_NUMBER = 1;
        private long id_;

        /**
         * <code>uint64 id = 1;</code>
         */
        public long getId() {
            return id_;
        }

        public static final int BRW_NAME_FIELD_NUMBER = 2;
        private volatile java.lang.Object brwName_;

        /**
         * <code>string brw_name = 2;</code>
         */
        public java.lang.String getBrwName() {
            java.lang.Object ref = brwName_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                brwName_ = s;
                return s;
            }
        }

        /**
         * <code>string brw_name = 2;</code>
         */
        public com.google.protobuf.ByteString
        getBrwNameBytes() {
            java.lang.Object ref = brwName_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                brwName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int BRW_VERSION_FIELD_NUMBER = 3;
        private volatile java.lang.Object brwVersion_;

        /**
         * <code>string brw_version = 3;</code>
         */
        public java.lang.String getBrwVersion() {
            java.lang.Object ref = brwVersion_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                brwVersion_ = s;
                return s;
            }
        }

        /**
         * <code>string brw_version = 3;</code>
         */
        public com.google.protobuf.ByteString
        getBrwVersionBytes() {
            java.lang.Object ref = brwVersion_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                brwVersion_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int BRW_PLAT_FIELD_NUMBER = 4;
        private volatile java.lang.Object brwPlat_;

        /**
         * <code>string brw_plat = 4;</code>
         */
        public java.lang.String getBrwPlat() {
            java.lang.Object ref = brwPlat_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                brwPlat_ = s;
                return s;
            }
        }

        /**
         * <code>string brw_plat = 4;</code>
         */
        public com.google.protobuf.ByteString
        getBrwPlatBytes() {
            java.lang.Object ref = brwPlat_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                brwPlat_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int BRW_NUM_FIELD_NUMBER = 5;
        private long brwNum_;

        /**
         * <code>uint64 brw_num = 5;</code>
         */
        public long getBrwNum() {
            return brwNum_;
        }

        public static final int UID_FIELD_NUMBER = 6;
        private long uid_;

        /**
         * <code>uint64 uid = 6;</code>
         */
        public long getUid() {
            return uid_;
        }

        public static final int ADD_TIME_FIELD_NUMBER = 7;
        private long addTime_;

        /**
         * <code>uint64 add_time = 7;</code>
         */
        public long getAddTime() {
            return addTime_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (id_ != 0L) {
                output.writeUInt64(1, id_);
            }
            if (!getBrwNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, brwName_);
            }
            if (!getBrwVersionBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, brwVersion_);
            }
            if (!getBrwPlatBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, brwPlat_);
            }
            if (brwNum_ != 0L) {
                output.writeUInt64(5, brwNum_);
            }
            if (uid_ != 0L) {
                output.writeUInt64(6, uid_);
            }
            if (addTime_ != 0L) {
                output.writeUInt64(7, addTime_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (id_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(1, id_);
            }
            if (!getBrwNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, brwName_);
            }
            if (!getBrwVersionBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, brwVersion_);
            }
            if (!getBrwPlatBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, brwPlat_);
            }
            if (brwNum_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(5, brwNum_);
            }
            if (uid_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(6, uid_);
            }
            if (addTime_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(7, addTime_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof io.union.log.common.proto.LogBrowserProto.LogBrowserMessage)) {
                return super.equals(obj);
            }
            io.union.log.common.proto.LogBrowserProto.LogBrowserMessage other = (io.union.log.common.proto.LogBrowserProto.LogBrowserMessage) obj;

            boolean result = true;
            result = result && (getId()
                    == other.getId());
            result = result && getBrwName()
                    .equals(other.getBrwName());
            result = result && getBrwVersion()
                    .equals(other.getBrwVersion());
            result = result && getBrwPlat()
                    .equals(other.getBrwPlat());
            result = result && (getBrwNum()
                    == other.getBrwNum());
            result = result && (getUid()
                    == other.getUid());
            result = result && (getAddTime()
                    == other.getAddTime());
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getId());
            hash = (37 * hash) + BRW_NAME_FIELD_NUMBER;
            hash = (53 * hash) + getBrwName().hashCode();
            hash = (37 * hash) + BRW_VERSION_FIELD_NUMBER;
            hash = (53 * hash) + getBrwVersion().hashCode();
            hash = (37 * hash) + BRW_PLAT_FIELD_NUMBER;
            hash = (53 * hash) + getBrwPlat().hashCode();
            hash = (37 * hash) + BRW_NUM_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getBrwNum());
            hash = (37 * hash) + UID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getUid());
            hash = (37 * hash) + ADD_TIME_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getAddTime());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static io.union.log.common.proto.LogBrowserProto.LogBrowserMessage parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.union.log.common.proto.LogBrowserProto.LogBrowserMessage parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.union.log.common.proto.LogBrowserProto.LogBrowserMessage parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.union.log.common.proto.LogBrowserProto.LogBrowserMessage parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.union.log.common.proto.LogBrowserProto.LogBrowserMessage parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.union.log.common.proto.LogBrowserProto.LogBrowserMessage parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.union.log.common.proto.LogBrowserProto.LogBrowserMessage parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static io.union.log.common.proto.LogBrowserProto.LogBrowserMessage parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static io.union.log.common.proto.LogBrowserProto.LogBrowserMessage parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static io.union.log.common.proto.LogBrowserProto.LogBrowserMessage parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static io.union.log.common.proto.LogBrowserProto.LogBrowserMessage parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static io.union.log.common.proto.LogBrowserProto.LogBrowserMessage parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(io.union.log.common.proto.LogBrowserProto.LogBrowserMessage prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code io.union.log.common.proto.LogBrowserMessage}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:io.union.log.common.proto.LogBrowserMessage)
                io.union.log.common.proto.LogBrowserProto.LogBrowserMessageOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return io.union.log.common.proto.LogBrowserProto.internal_static_io_union_log_common_proto_LogBrowserMessage_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return io.union.log.common.proto.LogBrowserProto.internal_static_io_union_log_common_proto_LogBrowserMessage_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                io.union.log.common.proto.LogBrowserProto.LogBrowserMessage.class, io.union.log.common.proto.LogBrowserProto.LogBrowserMessage.Builder.class);
            }

            // Construct using io.union.log.common.proto.LogBrowserProto.LogBrowserMessage.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                id_ = 0L;

                brwName_ = "";

                brwVersion_ = "";

                brwPlat_ = "";

                brwNum_ = 0L;

                uid_ = 0L;

                addTime_ = 0L;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return io.union.log.common.proto.LogBrowserProto.internal_static_io_union_log_common_proto_LogBrowserMessage_descriptor;
            }

            public io.union.log.common.proto.LogBrowserProto.LogBrowserMessage getDefaultInstanceForType() {
                return io.union.log.common.proto.LogBrowserProto.LogBrowserMessage.getDefaultInstance();
            }

            public io.union.log.common.proto.LogBrowserProto.LogBrowserMessage build() {
                io.union.log.common.proto.LogBrowserProto.LogBrowserMessage result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public io.union.log.common.proto.LogBrowserProto.LogBrowserMessage buildPartial() {
                io.union.log.common.proto.LogBrowserProto.LogBrowserMessage result = new io.union.log.common.proto.LogBrowserProto.LogBrowserMessage(this);
                result.id_ = id_;
                result.brwName_ = brwName_;
                result.brwVersion_ = brwVersion_;
                result.brwPlat_ = brwPlat_;
                result.brwNum_ = brwNum_;
                result.uid_ = uid_;
                result.addTime_ = addTime_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof io.union.log.common.proto.LogBrowserProto.LogBrowserMessage) {
                    return mergeFrom((io.union.log.common.proto.LogBrowserProto.LogBrowserMessage) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(io.union.log.common.proto.LogBrowserProto.LogBrowserMessage other) {
                if (other == io.union.log.common.proto.LogBrowserProto.LogBrowserMessage.getDefaultInstance())
                    return this;
                if (other.getId() != 0L) {
                    setId(other.getId());
                }
                if (!other.getBrwName().isEmpty()) {
                    brwName_ = other.brwName_;
                    onChanged();
                }
                if (!other.getBrwVersion().isEmpty()) {
                    brwVersion_ = other.brwVersion_;
                    onChanged();
                }
                if (!other.getBrwPlat().isEmpty()) {
                    brwPlat_ = other.brwPlat_;
                    onChanged();
                }
                if (other.getBrwNum() != 0L) {
                    setBrwNum(other.getBrwNum());
                }
                if (other.getUid() != 0L) {
                    setUid(other.getUid());
                }
                if (other.getAddTime() != 0L) {
                    setAddTime(other.getAddTime());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                io.union.log.common.proto.LogBrowserProto.LogBrowserMessage parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (io.union.log.common.proto.LogBrowserProto.LogBrowserMessage) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private long id_;

            /**
             * <code>uint64 id = 1;</code>
             */
            public long getId() {
                return id_;
            }

            /**
             * <code>uint64 id = 1;</code>
             */
            public Builder setId(long value) {

                id_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 id = 1;</code>
             */
            public Builder clearId() {

                id_ = 0L;
                onChanged();
                return this;
            }

            private java.lang.Object brwName_ = "";

            /**
             * <code>string brw_name = 2;</code>
             */
            public java.lang.String getBrwName() {
                java.lang.Object ref = brwName_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    brwName_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string brw_name = 2;</code>
             */
            public com.google.protobuf.ByteString
            getBrwNameBytes() {
                java.lang.Object ref = brwName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    brwName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string brw_name = 2;</code>
             */
            public Builder setBrwName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                brwName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string brw_name = 2;</code>
             */
            public Builder clearBrwName() {

                brwName_ = getDefaultInstance().getBrwName();
                onChanged();
                return this;
            }

            /**
             * <code>string brw_name = 2;</code>
             */
            public Builder setBrwNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                brwName_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object brwVersion_ = "";

            /**
             * <code>string brw_version = 3;</code>
             */
            public java.lang.String getBrwVersion() {
                java.lang.Object ref = brwVersion_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    brwVersion_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string brw_version = 3;</code>
             */
            public com.google.protobuf.ByteString
            getBrwVersionBytes() {
                java.lang.Object ref = brwVersion_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    brwVersion_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string brw_version = 3;</code>
             */
            public Builder setBrwVersion(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                brwVersion_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string brw_version = 3;</code>
             */
            public Builder clearBrwVersion() {

                brwVersion_ = getDefaultInstance().getBrwVersion();
                onChanged();
                return this;
            }

            /**
             * <code>string brw_version = 3;</code>
             */
            public Builder setBrwVersionBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                brwVersion_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object brwPlat_ = "";

            /**
             * <code>string brw_plat = 4;</code>
             */
            public java.lang.String getBrwPlat() {
                java.lang.Object ref = brwPlat_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    brwPlat_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string brw_plat = 4;</code>
             */
            public com.google.protobuf.ByteString
            getBrwPlatBytes() {
                java.lang.Object ref = brwPlat_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    brwPlat_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string brw_plat = 4;</code>
             */
            public Builder setBrwPlat(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                brwPlat_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string brw_plat = 4;</code>
             */
            public Builder clearBrwPlat() {

                brwPlat_ = getDefaultInstance().getBrwPlat();
                onChanged();
                return this;
            }

            /**
             * <code>string brw_plat = 4;</code>
             */
            public Builder setBrwPlatBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                brwPlat_ = value;
                onChanged();
                return this;
            }

            private long brwNum_;

            /**
             * <code>uint64 brw_num = 5;</code>
             */
            public long getBrwNum() {
                return brwNum_;
            }

            /**
             * <code>uint64 brw_num = 5;</code>
             */
            public Builder setBrwNum(long value) {

                brwNum_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 brw_num = 5;</code>
             */
            public Builder clearBrwNum() {

                brwNum_ = 0L;
                onChanged();
                return this;
            }

            private long uid_;

            /**
             * <code>uint64 uid = 6;</code>
             */
            public long getUid() {
                return uid_;
            }

            /**
             * <code>uint64 uid = 6;</code>
             */
            public Builder setUid(long value) {

                uid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 uid = 6;</code>
             */
            public Builder clearUid() {

                uid_ = 0L;
                onChanged();
                return this;
            }

            private long addTime_;

            /**
             * <code>uint64 add_time = 7;</code>
             */
            public long getAddTime() {
                return addTime_;
            }

            /**
             * <code>uint64 add_time = 7;</code>
             */
            public Builder setAddTime(long value) {

                addTime_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 add_time = 7;</code>
             */
            public Builder clearAddTime() {

                addTime_ = 0L;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:io.union.log.common.proto.LogBrowserMessage)
        }

        // @@protoc_insertion_point(class_scope:io.union.log.common.proto.LogBrowserMessage)
        private static final io.union.log.common.proto.LogBrowserProto.LogBrowserMessage DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new io.union.log.common.proto.LogBrowserProto.LogBrowserMessage();
        }

        public static io.union.log.common.proto.LogBrowserProto.LogBrowserMessage getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<LogBrowserMessage>
                PARSER = new com.google.protobuf.AbstractParser<LogBrowserMessage>() {
            public LogBrowserMessage parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new LogBrowserMessage(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<LogBrowserMessage> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<LogBrowserMessage> getParserForType() {
            return PARSER;
        }

        public io.union.log.common.proto.LogBrowserProto.LogBrowserMessage getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_io_union_log_common_proto_LogBrowserMessage_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_io_union_log_common_proto_LogBrowserMessage_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\020LogBrowser.proto\022\031io.union.log.common." +
                        "proto\"\210\001\n\021LogBrowserMessage\022\n\n\002id\030\001 \001(\004\022" +
                        "\020\n\010brw_name\030\002 \001(\t\022\023\n\013brw_version\030\003 \001(\t\022\020" +
                        "\n\010brw_plat\030\004 \001(\t\022\017\n\007brw_num\030\005 \001(\004\022\013\n\003uid" +
                        "\030\006 \001(\004\022\020\n\010add_time\030\007 \001(\004B,\n\031io.union.log" +
                        ".common.protoB\017LogBrowserProtob\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_io_union_log_common_proto_LogBrowserMessage_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_io_union_log_common_proto_LogBrowserMessage_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_io_union_log_common_proto_LogBrowserMessage_descriptor,
                new java.lang.String[]{"Id", "BrwName", "BrwVersion", "BrwPlat", "BrwNum", "Uid", "AddTime",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
