// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StatHourMoney.proto

package io.union.log.common.proto;

public final class StatHourMoneyProto {
    private StatHourMoneyProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface StatHourMoneyMessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:io.union.log.common.proto.StatHourMoneyMessage)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>uint64 id = 1;</code>
         */
        long getId();

        /**
         * <code>uint64 uid = 2;</code>
         */
        long getUid();

        /**
         * <code>uint64 siteid = 3;</code>
         */
        long getSiteid();

        /**
         * <code>uint64 planid = 4;</code>
         */
        long getPlanid();

        /**
         * <code>uint64 add_time = 5;</code>
         */
        long getAddTime();

        /**
         * <code>double hour0 = 6;</code>
         */
        double getHour0();

        /**
         * <code>double hour1 = 7;</code>
         */
        double getHour1();

        /**
         * <code>double hour2 = 8;</code>
         */
        double getHour2();

        /**
         * <code>double hour3 = 9;</code>
         */
        double getHour3();

        /**
         * <code>double hour4 = 10;</code>
         */
        double getHour4();

        /**
         * <code>double hour5 = 11;</code>
         */
        double getHour5();

        /**
         * <code>double hour6 = 12;</code>
         */
        double getHour6();

        /**
         * <code>double hour7 = 13;</code>
         */
        double getHour7();

        /**
         * <code>double hour8 = 14;</code>
         */
        double getHour8();

        /**
         * <code>double hour9 = 15;</code>
         */
        double getHour9();

        /**
         * <code>double hour10 = 16;</code>
         */
        double getHour10();

        /**
         * <code>double hour11 = 17;</code>
         */
        double getHour11();

        /**
         * <code>double hour12 = 18;</code>
         */
        double getHour12();

        /**
         * <code>double hour13 = 19;</code>
         */
        double getHour13();

        /**
         * <code>double hour14 = 20;</code>
         */
        double getHour14();

        /**
         * <code>double hour15 = 21;</code>
         */
        double getHour15();

        /**
         * <code>double hour16 = 22;</code>
         */
        double getHour16();

        /**
         * <code>double hour17 = 23;</code>
         */
        double getHour17();

        /**
         * <code>double hour18 = 24;</code>
         */
        double getHour18();

        /**
         * <code>double hour19 = 25;</code>
         */
        double getHour19();

        /**
         * <code>double hour20 = 26;</code>
         */
        double getHour20();

        /**
         * <code>double hour21 = 27;</code>
         */
        double getHour21();

        /**
         * <code>double hour22 = 28;</code>
         */
        double getHour22();

        /**
         * <code>double hour23 = 29;</code>
         */
        double getHour23();
    }

    /**
     * Protobuf type {@code io.union.log.common.proto.StatHourMoneyMessage}
     */
    public static final class StatHourMoneyMessage extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:io.union.log.common.proto.StatHourMoneyMessage)
            StatHourMoneyMessageOrBuilder {
        // Use StatHourMoneyMessage.newBuilder() to construct.
        private StatHourMoneyMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private StatHourMoneyMessage() {
            id_ = 0L;
            uid_ = 0L;
            siteid_ = 0L;
            planid_ = 0L;
            addTime_ = 0L;
            hour0_ = 0D;
            hour1_ = 0D;
            hour2_ = 0D;
            hour3_ = 0D;
            hour4_ = 0D;
            hour5_ = 0D;
            hour6_ = 0D;
            hour7_ = 0D;
            hour8_ = 0D;
            hour9_ = 0D;
            hour10_ = 0D;
            hour11_ = 0D;
            hour12_ = 0D;
            hour13_ = 0D;
            hour14_ = 0D;
            hour15_ = 0D;
            hour16_ = 0D;
            hour17_ = 0D;
            hour18_ = 0D;
            hour19_ = 0D;
            hour20_ = 0D;
            hour21_ = 0D;
            hour22_ = 0D;
            hour23_ = 0D;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private StatHourMoneyMessage(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            id_ = input.readUInt64();
                            break;
                        }
                        case 16: {

                            uid_ = input.readUInt64();
                            break;
                        }
                        case 24: {

                            siteid_ = input.readUInt64();
                            break;
                        }
                        case 32: {

                            planid_ = input.readUInt64();
                            break;
                        }
                        case 40: {

                            addTime_ = input.readUInt64();
                            break;
                        }
                        case 49: {

                            hour0_ = input.readDouble();
                            break;
                        }
                        case 57: {

                            hour1_ = input.readDouble();
                            break;
                        }
                        case 65: {

                            hour2_ = input.readDouble();
                            break;
                        }
                        case 73: {

                            hour3_ = input.readDouble();
                            break;
                        }
                        case 81: {

                            hour4_ = input.readDouble();
                            break;
                        }
                        case 89: {

                            hour5_ = input.readDouble();
                            break;
                        }
                        case 97: {

                            hour6_ = input.readDouble();
                            break;
                        }
                        case 105: {

                            hour7_ = input.readDouble();
                            break;
                        }
                        case 113: {

                            hour8_ = input.readDouble();
                            break;
                        }
                        case 121: {

                            hour9_ = input.readDouble();
                            break;
                        }
                        case 129: {

                            hour10_ = input.readDouble();
                            break;
                        }
                        case 137: {

                            hour11_ = input.readDouble();
                            break;
                        }
                        case 145: {

                            hour12_ = input.readDouble();
                            break;
                        }
                        case 153: {

                            hour13_ = input.readDouble();
                            break;
                        }
                        case 161: {

                            hour14_ = input.readDouble();
                            break;
                        }
                        case 169: {

                            hour15_ = input.readDouble();
                            break;
                        }
                        case 177: {

                            hour16_ = input.readDouble();
                            break;
                        }
                        case 185: {

                            hour17_ = input.readDouble();
                            break;
                        }
                        case 193: {

                            hour18_ = input.readDouble();
                            break;
                        }
                        case 201: {

                            hour19_ = input.readDouble();
                            break;
                        }
                        case 209: {

                            hour20_ = input.readDouble();
                            break;
                        }
                        case 217: {

                            hour21_ = input.readDouble();
                            break;
                        }
                        case 225: {

                            hour22_ = input.readDouble();
                            break;
                        }
                        case 233: {

                            hour23_ = input.readDouble();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return io.union.log.common.proto.StatHourMoneyProto.internal_static_io_union_log_common_proto_StatHourMoneyMessage_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return io.union.log.common.proto.StatHourMoneyProto.internal_static_io_union_log_common_proto_StatHourMoneyMessage_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage.class, io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage.Builder.class);
        }

        public static final int ID_FIELD_NUMBER = 1;
        private long id_;

        /**
         * <code>uint64 id = 1;</code>
         */
        public long getId() {
            return id_;
        }

        public static final int UID_FIELD_NUMBER = 2;
        private long uid_;

        /**
         * <code>uint64 uid = 2;</code>
         */
        public long getUid() {
            return uid_;
        }

        public static final int SITEID_FIELD_NUMBER = 3;
        private long siteid_;

        /**
         * <code>uint64 siteid = 3;</code>
         */
        public long getSiteid() {
            return siteid_;
        }

        public static final int PLANID_FIELD_NUMBER = 4;
        private long planid_;

        /**
         * <code>uint64 planid = 4;</code>
         */
        public long getPlanid() {
            return planid_;
        }

        public static final int ADD_TIME_FIELD_NUMBER = 5;
        private long addTime_;

        /**
         * <code>uint64 add_time = 5;</code>
         */
        public long getAddTime() {
            return addTime_;
        }

        public static final int HOUR0_FIELD_NUMBER = 6;
        private double hour0_;

        /**
         * <code>double hour0 = 6;</code>
         */
        public double getHour0() {
            return hour0_;
        }

        public static final int HOUR1_FIELD_NUMBER = 7;
        private double hour1_;

        /**
         * <code>double hour1 = 7;</code>
         */
        public double getHour1() {
            return hour1_;
        }

        public static final int HOUR2_FIELD_NUMBER = 8;
        private double hour2_;

        /**
         * <code>double hour2 = 8;</code>
         */
        public double getHour2() {
            return hour2_;
        }

        public static final int HOUR3_FIELD_NUMBER = 9;
        private double hour3_;

        /**
         * <code>double hour3 = 9;</code>
         */
        public double getHour3() {
            return hour3_;
        }

        public static final int HOUR4_FIELD_NUMBER = 10;
        private double hour4_;

        /**
         * <code>double hour4 = 10;</code>
         */
        public double getHour4() {
            return hour4_;
        }

        public static final int HOUR5_FIELD_NUMBER = 11;
        private double hour5_;

        /**
         * <code>double hour5 = 11;</code>
         */
        public double getHour5() {
            return hour5_;
        }

        public static final int HOUR6_FIELD_NUMBER = 12;
        private double hour6_;

        /**
         * <code>double hour6 = 12;</code>
         */
        public double getHour6() {
            return hour6_;
        }

        public static final int HOUR7_FIELD_NUMBER = 13;
        private double hour7_;

        /**
         * <code>double hour7 = 13;</code>
         */
        public double getHour7() {
            return hour7_;
        }

        public static final int HOUR8_FIELD_NUMBER = 14;
        private double hour8_;

        /**
         * <code>double hour8 = 14;</code>
         */
        public double getHour8() {
            return hour8_;
        }

        public static final int HOUR9_FIELD_NUMBER = 15;
        private double hour9_;

        /**
         * <code>double hour9 = 15;</code>
         */
        public double getHour9() {
            return hour9_;
        }

        public static final int HOUR10_FIELD_NUMBER = 16;
        private double hour10_;

        /**
         * <code>double hour10 = 16;</code>
         */
        public double getHour10() {
            return hour10_;
        }

        public static final int HOUR11_FIELD_NUMBER = 17;
        private double hour11_;

        /**
         * <code>double hour11 = 17;</code>
         */
        public double getHour11() {
            return hour11_;
        }

        public static final int HOUR12_FIELD_NUMBER = 18;
        private double hour12_;

        /**
         * <code>double hour12 = 18;</code>
         */
        public double getHour12() {
            return hour12_;
        }

        public static final int HOUR13_FIELD_NUMBER = 19;
        private double hour13_;

        /**
         * <code>double hour13 = 19;</code>
         */
        public double getHour13() {
            return hour13_;
        }

        public static final int HOUR14_FIELD_NUMBER = 20;
        private double hour14_;

        /**
         * <code>double hour14 = 20;</code>
         */
        public double getHour14() {
            return hour14_;
        }

        public static final int HOUR15_FIELD_NUMBER = 21;
        private double hour15_;

        /**
         * <code>double hour15 = 21;</code>
         */
        public double getHour15() {
            return hour15_;
        }

        public static final int HOUR16_FIELD_NUMBER = 22;
        private double hour16_;

        /**
         * <code>double hour16 = 22;</code>
         */
        public double getHour16() {
            return hour16_;
        }

        public static final int HOUR17_FIELD_NUMBER = 23;
        private double hour17_;

        /**
         * <code>double hour17 = 23;</code>
         */
        public double getHour17() {
            return hour17_;
        }

        public static final int HOUR18_FIELD_NUMBER = 24;
        private double hour18_;

        /**
         * <code>double hour18 = 24;</code>
         */
        public double getHour18() {
            return hour18_;
        }

        public static final int HOUR19_FIELD_NUMBER = 25;
        private double hour19_;

        /**
         * <code>double hour19 = 25;</code>
         */
        public double getHour19() {
            return hour19_;
        }

        public static final int HOUR20_FIELD_NUMBER = 26;
        private double hour20_;

        /**
         * <code>double hour20 = 26;</code>
         */
        public double getHour20() {
            return hour20_;
        }

        public static final int HOUR21_FIELD_NUMBER = 27;
        private double hour21_;

        /**
         * <code>double hour21 = 27;</code>
         */
        public double getHour21() {
            return hour21_;
        }

        public static final int HOUR22_FIELD_NUMBER = 28;
        private double hour22_;

        /**
         * <code>double hour22 = 28;</code>
         */
        public double getHour22() {
            return hour22_;
        }

        public static final int HOUR23_FIELD_NUMBER = 29;
        private double hour23_;

        /**
         * <code>double hour23 = 29;</code>
         */
        public double getHour23() {
            return hour23_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (id_ != 0L) {
                output.writeUInt64(1, id_);
            }
            if (uid_ != 0L) {
                output.writeUInt64(2, uid_);
            }
            if (siteid_ != 0L) {
                output.writeUInt64(3, siteid_);
            }
            if (planid_ != 0L) {
                output.writeUInt64(4, planid_);
            }
            if (addTime_ != 0L) {
                output.writeUInt64(5, addTime_);
            }
            if (hour0_ != 0D) {
                output.writeDouble(6, hour0_);
            }
            if (hour1_ != 0D) {
                output.writeDouble(7, hour1_);
            }
            if (hour2_ != 0D) {
                output.writeDouble(8, hour2_);
            }
            if (hour3_ != 0D) {
                output.writeDouble(9, hour3_);
            }
            if (hour4_ != 0D) {
                output.writeDouble(10, hour4_);
            }
            if (hour5_ != 0D) {
                output.writeDouble(11, hour5_);
            }
            if (hour6_ != 0D) {
                output.writeDouble(12, hour6_);
            }
            if (hour7_ != 0D) {
                output.writeDouble(13, hour7_);
            }
            if (hour8_ != 0D) {
                output.writeDouble(14, hour8_);
            }
            if (hour9_ != 0D) {
                output.writeDouble(15, hour9_);
            }
            if (hour10_ != 0D) {
                output.writeDouble(16, hour10_);
            }
            if (hour11_ != 0D) {
                output.writeDouble(17, hour11_);
            }
            if (hour12_ != 0D) {
                output.writeDouble(18, hour12_);
            }
            if (hour13_ != 0D) {
                output.writeDouble(19, hour13_);
            }
            if (hour14_ != 0D) {
                output.writeDouble(20, hour14_);
            }
            if (hour15_ != 0D) {
                output.writeDouble(21, hour15_);
            }
            if (hour16_ != 0D) {
                output.writeDouble(22, hour16_);
            }
            if (hour17_ != 0D) {
                output.writeDouble(23, hour17_);
            }
            if (hour18_ != 0D) {
                output.writeDouble(24, hour18_);
            }
            if (hour19_ != 0D) {
                output.writeDouble(25, hour19_);
            }
            if (hour20_ != 0D) {
                output.writeDouble(26, hour20_);
            }
            if (hour21_ != 0D) {
                output.writeDouble(27, hour21_);
            }
            if (hour22_ != 0D) {
                output.writeDouble(28, hour22_);
            }
            if (hour23_ != 0D) {
                output.writeDouble(29, hour23_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (id_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(1, id_);
            }
            if (uid_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(2, uid_);
            }
            if (siteid_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(3, siteid_);
            }
            if (planid_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(4, planid_);
            }
            if (addTime_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(5, addTime_);
            }
            if (hour0_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(6, hour0_);
            }
            if (hour1_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(7, hour1_);
            }
            if (hour2_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(8, hour2_);
            }
            if (hour3_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(9, hour3_);
            }
            if (hour4_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(10, hour4_);
            }
            if (hour5_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(11, hour5_);
            }
            if (hour6_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(12, hour6_);
            }
            if (hour7_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(13, hour7_);
            }
            if (hour8_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(14, hour8_);
            }
            if (hour9_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(15, hour9_);
            }
            if (hour10_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(16, hour10_);
            }
            if (hour11_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(17, hour11_);
            }
            if (hour12_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(18, hour12_);
            }
            if (hour13_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(19, hour13_);
            }
            if (hour14_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(20, hour14_);
            }
            if (hour15_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(21, hour15_);
            }
            if (hour16_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(22, hour16_);
            }
            if (hour17_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(23, hour17_);
            }
            if (hour18_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(24, hour18_);
            }
            if (hour19_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(25, hour19_);
            }
            if (hour20_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(26, hour20_);
            }
            if (hour21_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(27, hour21_);
            }
            if (hour22_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(28, hour22_);
            }
            if (hour23_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(29, hour23_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage)) {
                return super.equals(obj);
            }
            io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage other = (io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage) obj;

            boolean result = true;
            result = result && (getId()
                    == other.getId());
            result = result && (getUid()
                    == other.getUid());
            result = result && (getSiteid()
                    == other.getSiteid());
            result = result && (getPlanid()
                    == other.getPlanid());
            result = result && (getAddTime()
                    == other.getAddTime());
            result = result && (
                    java.lang.Double.doubleToLongBits(getHour0())
                            == java.lang.Double.doubleToLongBits(
                            other.getHour0()));
            result = result && (
                    java.lang.Double.doubleToLongBits(getHour1())
                            == java.lang.Double.doubleToLongBits(
                            other.getHour1()));
            result = result && (
                    java.lang.Double.doubleToLongBits(getHour2())
                            == java.lang.Double.doubleToLongBits(
                            other.getHour2()));
            result = result && (
                    java.lang.Double.doubleToLongBits(getHour3())
                            == java.lang.Double.doubleToLongBits(
                            other.getHour3()));
            result = result && (
                    java.lang.Double.doubleToLongBits(getHour4())
                            == java.lang.Double.doubleToLongBits(
                            other.getHour4()));
            result = result && (
                    java.lang.Double.doubleToLongBits(getHour5())
                            == java.lang.Double.doubleToLongBits(
                            other.getHour5()));
            result = result && (
                    java.lang.Double.doubleToLongBits(getHour6())
                            == java.lang.Double.doubleToLongBits(
                            other.getHour6()));
            result = result && (
                    java.lang.Double.doubleToLongBits(getHour7())
                            == java.lang.Double.doubleToLongBits(
                            other.getHour7()));
            result = result && (
                    java.lang.Double.doubleToLongBits(getHour8())
                            == java.lang.Double.doubleToLongBits(
                            other.getHour8()));
            result = result && (
                    java.lang.Double.doubleToLongBits(getHour9())
                            == java.lang.Double.doubleToLongBits(
                            other.getHour9()));
            result = result && (
                    java.lang.Double.doubleToLongBits(getHour10())
                            == java.lang.Double.doubleToLongBits(
                            other.getHour10()));
            result = result && (
                    java.lang.Double.doubleToLongBits(getHour11())
                            == java.lang.Double.doubleToLongBits(
                            other.getHour11()));
            result = result && (
                    java.lang.Double.doubleToLongBits(getHour12())
                            == java.lang.Double.doubleToLongBits(
                            other.getHour12()));
            result = result && (
                    java.lang.Double.doubleToLongBits(getHour13())
                            == java.lang.Double.doubleToLongBits(
                            other.getHour13()));
            result = result && (
                    java.lang.Double.doubleToLongBits(getHour14())
                            == java.lang.Double.doubleToLongBits(
                            other.getHour14()));
            result = result && (
                    java.lang.Double.doubleToLongBits(getHour15())
                            == java.lang.Double.doubleToLongBits(
                            other.getHour15()));
            result = result && (
                    java.lang.Double.doubleToLongBits(getHour16())
                            == java.lang.Double.doubleToLongBits(
                            other.getHour16()));
            result = result && (
                    java.lang.Double.doubleToLongBits(getHour17())
                            == java.lang.Double.doubleToLongBits(
                            other.getHour17()));
            result = result && (
                    java.lang.Double.doubleToLongBits(getHour18())
                            == java.lang.Double.doubleToLongBits(
                            other.getHour18()));
            result = result && (
                    java.lang.Double.doubleToLongBits(getHour19())
                            == java.lang.Double.doubleToLongBits(
                            other.getHour19()));
            result = result && (
                    java.lang.Double.doubleToLongBits(getHour20())
                            == java.lang.Double.doubleToLongBits(
                            other.getHour20()));
            result = result && (
                    java.lang.Double.doubleToLongBits(getHour21())
                            == java.lang.Double.doubleToLongBits(
                            other.getHour21()));
            result = result && (
                    java.lang.Double.doubleToLongBits(getHour22())
                            == java.lang.Double.doubleToLongBits(
                            other.getHour22()));
            result = result && (
                    java.lang.Double.doubleToLongBits(getHour23())
                            == java.lang.Double.doubleToLongBits(
                            other.getHour23()));
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getId());
            hash = (37 * hash) + UID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getUid());
            hash = (37 * hash) + SITEID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getSiteid());
            hash = (37 * hash) + PLANID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getPlanid());
            hash = (37 * hash) + ADD_TIME_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getAddTime());
            hash = (37 * hash) + HOUR0_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getHour0()));
            hash = (37 * hash) + HOUR1_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getHour1()));
            hash = (37 * hash) + HOUR2_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getHour2()));
            hash = (37 * hash) + HOUR3_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getHour3()));
            hash = (37 * hash) + HOUR4_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getHour4()));
            hash = (37 * hash) + HOUR5_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getHour5()));
            hash = (37 * hash) + HOUR6_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getHour6()));
            hash = (37 * hash) + HOUR7_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getHour7()));
            hash = (37 * hash) + HOUR8_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getHour8()));
            hash = (37 * hash) + HOUR9_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getHour9()));
            hash = (37 * hash) + HOUR10_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getHour10()));
            hash = (37 * hash) + HOUR11_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getHour11()));
            hash = (37 * hash) + HOUR12_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getHour12()));
            hash = (37 * hash) + HOUR13_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getHour13()));
            hash = (37 * hash) + HOUR14_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getHour14()));
            hash = (37 * hash) + HOUR15_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getHour15()));
            hash = (37 * hash) + HOUR16_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getHour16()));
            hash = (37 * hash) + HOUR17_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getHour17()));
            hash = (37 * hash) + HOUR18_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getHour18()));
            hash = (37 * hash) + HOUR19_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getHour19()));
            hash = (37 * hash) + HOUR20_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getHour20()));
            hash = (37 * hash) + HOUR21_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getHour21()));
            hash = (37 * hash) + HOUR22_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getHour22()));
            hash = (37 * hash) + HOUR23_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getHour23()));
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code io.union.log.common.proto.StatHourMoneyMessage}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:io.union.log.common.proto.StatHourMoneyMessage)
                io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessageOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return io.union.log.common.proto.StatHourMoneyProto.internal_static_io_union_log_common_proto_StatHourMoneyMessage_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return io.union.log.common.proto.StatHourMoneyProto.internal_static_io_union_log_common_proto_StatHourMoneyMessage_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage.class, io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage.Builder.class);
            }

            // Construct using io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                id_ = 0L;

                uid_ = 0L;

                siteid_ = 0L;

                planid_ = 0L;

                addTime_ = 0L;

                hour0_ = 0D;

                hour1_ = 0D;

                hour2_ = 0D;

                hour3_ = 0D;

                hour4_ = 0D;

                hour5_ = 0D;

                hour6_ = 0D;

                hour7_ = 0D;

                hour8_ = 0D;

                hour9_ = 0D;

                hour10_ = 0D;

                hour11_ = 0D;

                hour12_ = 0D;

                hour13_ = 0D;

                hour14_ = 0D;

                hour15_ = 0D;

                hour16_ = 0D;

                hour17_ = 0D;

                hour18_ = 0D;

                hour19_ = 0D;

                hour20_ = 0D;

                hour21_ = 0D;

                hour22_ = 0D;

                hour23_ = 0D;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return io.union.log.common.proto.StatHourMoneyProto.internal_static_io_union_log_common_proto_StatHourMoneyMessage_descriptor;
            }

            public io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage getDefaultInstanceForType() {
                return io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage.getDefaultInstance();
            }

            public io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage build() {
                io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage buildPartial() {
                io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage result = new io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage(this);
                result.id_ = id_;
                result.uid_ = uid_;
                result.siteid_ = siteid_;
                result.planid_ = planid_;
                result.addTime_ = addTime_;
                result.hour0_ = hour0_;
                result.hour1_ = hour1_;
                result.hour2_ = hour2_;
                result.hour3_ = hour3_;
                result.hour4_ = hour4_;
                result.hour5_ = hour5_;
                result.hour6_ = hour6_;
                result.hour7_ = hour7_;
                result.hour8_ = hour8_;
                result.hour9_ = hour9_;
                result.hour10_ = hour10_;
                result.hour11_ = hour11_;
                result.hour12_ = hour12_;
                result.hour13_ = hour13_;
                result.hour14_ = hour14_;
                result.hour15_ = hour15_;
                result.hour16_ = hour16_;
                result.hour17_ = hour17_;
                result.hour18_ = hour18_;
                result.hour19_ = hour19_;
                result.hour20_ = hour20_;
                result.hour21_ = hour21_;
                result.hour22_ = hour22_;
                result.hour23_ = hour23_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage) {
                    return mergeFrom((io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage other) {
                if (other == io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage.getDefaultInstance())
                    return this;
                if (other.getId() != 0L) {
                    setId(other.getId());
                }
                if (other.getUid() != 0L) {
                    setUid(other.getUid());
                }
                if (other.getSiteid() != 0L) {
                    setSiteid(other.getSiteid());
                }
                if (other.getPlanid() != 0L) {
                    setPlanid(other.getPlanid());
                }
                if (other.getAddTime() != 0L) {
                    setAddTime(other.getAddTime());
                }
                if (other.getHour0() != 0D) {
                    setHour0(other.getHour0());
                }
                if (other.getHour1() != 0D) {
                    setHour1(other.getHour1());
                }
                if (other.getHour2() != 0D) {
                    setHour2(other.getHour2());
                }
                if (other.getHour3() != 0D) {
                    setHour3(other.getHour3());
                }
                if (other.getHour4() != 0D) {
                    setHour4(other.getHour4());
                }
                if (other.getHour5() != 0D) {
                    setHour5(other.getHour5());
                }
                if (other.getHour6() != 0D) {
                    setHour6(other.getHour6());
                }
                if (other.getHour7() != 0D) {
                    setHour7(other.getHour7());
                }
                if (other.getHour8() != 0D) {
                    setHour8(other.getHour8());
                }
                if (other.getHour9() != 0D) {
                    setHour9(other.getHour9());
                }
                if (other.getHour10() != 0D) {
                    setHour10(other.getHour10());
                }
                if (other.getHour11() != 0D) {
                    setHour11(other.getHour11());
                }
                if (other.getHour12() != 0D) {
                    setHour12(other.getHour12());
                }
                if (other.getHour13() != 0D) {
                    setHour13(other.getHour13());
                }
                if (other.getHour14() != 0D) {
                    setHour14(other.getHour14());
                }
                if (other.getHour15() != 0D) {
                    setHour15(other.getHour15());
                }
                if (other.getHour16() != 0D) {
                    setHour16(other.getHour16());
                }
                if (other.getHour17() != 0D) {
                    setHour17(other.getHour17());
                }
                if (other.getHour18() != 0D) {
                    setHour18(other.getHour18());
                }
                if (other.getHour19() != 0D) {
                    setHour19(other.getHour19());
                }
                if (other.getHour20() != 0D) {
                    setHour20(other.getHour20());
                }
                if (other.getHour21() != 0D) {
                    setHour21(other.getHour21());
                }
                if (other.getHour22() != 0D) {
                    setHour22(other.getHour22());
                }
                if (other.getHour23() != 0D) {
                    setHour23(other.getHour23());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private long id_;

            /**
             * <code>uint64 id = 1;</code>
             */
            public long getId() {
                return id_;
            }

            /**
             * <code>uint64 id = 1;</code>
             */
            public Builder setId(long value) {

                id_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 id = 1;</code>
             */
            public Builder clearId() {

                id_ = 0L;
                onChanged();
                return this;
            }

            private long uid_;

            /**
             * <code>uint64 uid = 2;</code>
             */
            public long getUid() {
                return uid_;
            }

            /**
             * <code>uint64 uid = 2;</code>
             */
            public Builder setUid(long value) {

                uid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 uid = 2;</code>
             */
            public Builder clearUid() {

                uid_ = 0L;
                onChanged();
                return this;
            }

            private long siteid_;

            /**
             * <code>uint64 siteid = 3;</code>
             */
            public long getSiteid() {
                return siteid_;
            }

            /**
             * <code>uint64 siteid = 3;</code>
             */
            public Builder setSiteid(long value) {

                siteid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 siteid = 3;</code>
             */
            public Builder clearSiteid() {

                siteid_ = 0L;
                onChanged();
                return this;
            }

            private long planid_;

            /**
             * <code>uint64 planid = 4;</code>
             */
            public long getPlanid() {
                return planid_;
            }

            /**
             * <code>uint64 planid = 4;</code>
             */
            public Builder setPlanid(long value) {

                planid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 planid = 4;</code>
             */
            public Builder clearPlanid() {

                planid_ = 0L;
                onChanged();
                return this;
            }

            private long addTime_;

            /**
             * <code>uint64 add_time = 5;</code>
             */
            public long getAddTime() {
                return addTime_;
            }

            /**
             * <code>uint64 add_time = 5;</code>
             */
            public Builder setAddTime(long value) {

                addTime_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 add_time = 5;</code>
             */
            public Builder clearAddTime() {

                addTime_ = 0L;
                onChanged();
                return this;
            }

            private double hour0_;

            /**
             * <code>double hour0 = 6;</code>
             */
            public double getHour0() {
                return hour0_;
            }

            /**
             * <code>double hour0 = 6;</code>
             */
            public Builder setHour0(double value) {

                hour0_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double hour0 = 6;</code>
             */
            public Builder clearHour0() {

                hour0_ = 0D;
                onChanged();
                return this;
            }

            private double hour1_;

            /**
             * <code>double hour1 = 7;</code>
             */
            public double getHour1() {
                return hour1_;
            }

            /**
             * <code>double hour1 = 7;</code>
             */
            public Builder setHour1(double value) {

                hour1_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double hour1 = 7;</code>
             */
            public Builder clearHour1() {

                hour1_ = 0D;
                onChanged();
                return this;
            }

            private double hour2_;

            /**
             * <code>double hour2 = 8;</code>
             */
            public double getHour2() {
                return hour2_;
            }

            /**
             * <code>double hour2 = 8;</code>
             */
            public Builder setHour2(double value) {

                hour2_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double hour2 = 8;</code>
             */
            public Builder clearHour2() {

                hour2_ = 0D;
                onChanged();
                return this;
            }

            private double hour3_;

            /**
             * <code>double hour3 = 9;</code>
             */
            public double getHour3() {
                return hour3_;
            }

            /**
             * <code>double hour3 = 9;</code>
             */
            public Builder setHour3(double value) {

                hour3_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double hour3 = 9;</code>
             */
            public Builder clearHour3() {

                hour3_ = 0D;
                onChanged();
                return this;
            }

            private double hour4_;

            /**
             * <code>double hour4 = 10;</code>
             */
            public double getHour4() {
                return hour4_;
            }

            /**
             * <code>double hour4 = 10;</code>
             */
            public Builder setHour4(double value) {

                hour4_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double hour4 = 10;</code>
             */
            public Builder clearHour4() {

                hour4_ = 0D;
                onChanged();
                return this;
            }

            private double hour5_;

            /**
             * <code>double hour5 = 11;</code>
             */
            public double getHour5() {
                return hour5_;
            }

            /**
             * <code>double hour5 = 11;</code>
             */
            public Builder setHour5(double value) {

                hour5_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double hour5 = 11;</code>
             */
            public Builder clearHour5() {

                hour5_ = 0D;
                onChanged();
                return this;
            }

            private double hour6_;

            /**
             * <code>double hour6 = 12;</code>
             */
            public double getHour6() {
                return hour6_;
            }

            /**
             * <code>double hour6 = 12;</code>
             */
            public Builder setHour6(double value) {

                hour6_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double hour6 = 12;</code>
             */
            public Builder clearHour6() {

                hour6_ = 0D;
                onChanged();
                return this;
            }

            private double hour7_;

            /**
             * <code>double hour7 = 13;</code>
             */
            public double getHour7() {
                return hour7_;
            }

            /**
             * <code>double hour7 = 13;</code>
             */
            public Builder setHour7(double value) {

                hour7_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double hour7 = 13;</code>
             */
            public Builder clearHour7() {

                hour7_ = 0D;
                onChanged();
                return this;
            }

            private double hour8_;

            /**
             * <code>double hour8 = 14;</code>
             */
            public double getHour8() {
                return hour8_;
            }

            /**
             * <code>double hour8 = 14;</code>
             */
            public Builder setHour8(double value) {

                hour8_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double hour8 = 14;</code>
             */
            public Builder clearHour8() {

                hour8_ = 0D;
                onChanged();
                return this;
            }

            private double hour9_;

            /**
             * <code>double hour9 = 15;</code>
             */
            public double getHour9() {
                return hour9_;
            }

            /**
             * <code>double hour9 = 15;</code>
             */
            public Builder setHour9(double value) {

                hour9_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double hour9 = 15;</code>
             */
            public Builder clearHour9() {

                hour9_ = 0D;
                onChanged();
                return this;
            }

            private double hour10_;

            /**
             * <code>double hour10 = 16;</code>
             */
            public double getHour10() {
                return hour10_;
            }

            /**
             * <code>double hour10 = 16;</code>
             */
            public Builder setHour10(double value) {

                hour10_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double hour10 = 16;</code>
             */
            public Builder clearHour10() {

                hour10_ = 0D;
                onChanged();
                return this;
            }

            private double hour11_;

            /**
             * <code>double hour11 = 17;</code>
             */
            public double getHour11() {
                return hour11_;
            }

            /**
             * <code>double hour11 = 17;</code>
             */
            public Builder setHour11(double value) {

                hour11_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double hour11 = 17;</code>
             */
            public Builder clearHour11() {

                hour11_ = 0D;
                onChanged();
                return this;
            }

            private double hour12_;

            /**
             * <code>double hour12 = 18;</code>
             */
            public double getHour12() {
                return hour12_;
            }

            /**
             * <code>double hour12 = 18;</code>
             */
            public Builder setHour12(double value) {

                hour12_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double hour12 = 18;</code>
             */
            public Builder clearHour12() {

                hour12_ = 0D;
                onChanged();
                return this;
            }

            private double hour13_;

            /**
             * <code>double hour13 = 19;</code>
             */
            public double getHour13() {
                return hour13_;
            }

            /**
             * <code>double hour13 = 19;</code>
             */
            public Builder setHour13(double value) {

                hour13_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double hour13 = 19;</code>
             */
            public Builder clearHour13() {

                hour13_ = 0D;
                onChanged();
                return this;
            }

            private double hour14_;

            /**
             * <code>double hour14 = 20;</code>
             */
            public double getHour14() {
                return hour14_;
            }

            /**
             * <code>double hour14 = 20;</code>
             */
            public Builder setHour14(double value) {

                hour14_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double hour14 = 20;</code>
             */
            public Builder clearHour14() {

                hour14_ = 0D;
                onChanged();
                return this;
            }

            private double hour15_;

            /**
             * <code>double hour15 = 21;</code>
             */
            public double getHour15() {
                return hour15_;
            }

            /**
             * <code>double hour15 = 21;</code>
             */
            public Builder setHour15(double value) {

                hour15_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double hour15 = 21;</code>
             */
            public Builder clearHour15() {

                hour15_ = 0D;
                onChanged();
                return this;
            }

            private double hour16_;

            /**
             * <code>double hour16 = 22;</code>
             */
            public double getHour16() {
                return hour16_;
            }

            /**
             * <code>double hour16 = 22;</code>
             */
            public Builder setHour16(double value) {

                hour16_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double hour16 = 22;</code>
             */
            public Builder clearHour16() {

                hour16_ = 0D;
                onChanged();
                return this;
            }

            private double hour17_;

            /**
             * <code>double hour17 = 23;</code>
             */
            public double getHour17() {
                return hour17_;
            }

            /**
             * <code>double hour17 = 23;</code>
             */
            public Builder setHour17(double value) {

                hour17_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double hour17 = 23;</code>
             */
            public Builder clearHour17() {

                hour17_ = 0D;
                onChanged();
                return this;
            }

            private double hour18_;

            /**
             * <code>double hour18 = 24;</code>
             */
            public double getHour18() {
                return hour18_;
            }

            /**
             * <code>double hour18 = 24;</code>
             */
            public Builder setHour18(double value) {

                hour18_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double hour18 = 24;</code>
             */
            public Builder clearHour18() {

                hour18_ = 0D;
                onChanged();
                return this;
            }

            private double hour19_;

            /**
             * <code>double hour19 = 25;</code>
             */
            public double getHour19() {
                return hour19_;
            }

            /**
             * <code>double hour19 = 25;</code>
             */
            public Builder setHour19(double value) {

                hour19_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double hour19 = 25;</code>
             */
            public Builder clearHour19() {

                hour19_ = 0D;
                onChanged();
                return this;
            }

            private double hour20_;

            /**
             * <code>double hour20 = 26;</code>
             */
            public double getHour20() {
                return hour20_;
            }

            /**
             * <code>double hour20 = 26;</code>
             */
            public Builder setHour20(double value) {

                hour20_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double hour20 = 26;</code>
             */
            public Builder clearHour20() {

                hour20_ = 0D;
                onChanged();
                return this;
            }

            private double hour21_;

            /**
             * <code>double hour21 = 27;</code>
             */
            public double getHour21() {
                return hour21_;
            }

            /**
             * <code>double hour21 = 27;</code>
             */
            public Builder setHour21(double value) {

                hour21_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double hour21 = 27;</code>
             */
            public Builder clearHour21() {

                hour21_ = 0D;
                onChanged();
                return this;
            }

            private double hour22_;

            /**
             * <code>double hour22 = 28;</code>
             */
            public double getHour22() {
                return hour22_;
            }

            /**
             * <code>double hour22 = 28;</code>
             */
            public Builder setHour22(double value) {

                hour22_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double hour22 = 28;</code>
             */
            public Builder clearHour22() {

                hour22_ = 0D;
                onChanged();
                return this;
            }

            private double hour23_;

            /**
             * <code>double hour23 = 29;</code>
             */
            public double getHour23() {
                return hour23_;
            }

            /**
             * <code>double hour23 = 29;</code>
             */
            public Builder setHour23(double value) {

                hour23_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double hour23 = 29;</code>
             */
            public Builder clearHour23() {

                hour23_ = 0D;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:io.union.log.common.proto.StatHourMoneyMessage)
        }

        // @@protoc_insertion_point(class_scope:io.union.log.common.proto.StatHourMoneyMessage)
        private static final io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage();
        }

        public static io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<StatHourMoneyMessage>
                PARSER = new com.google.protobuf.AbstractParser<StatHourMoneyMessage>() {
            public StatHourMoneyMessage parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new StatHourMoneyMessage(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<StatHourMoneyMessage> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<StatHourMoneyMessage> getParserForType() {
            return PARSER;
        }

        public io.union.log.common.proto.StatHourMoneyProto.StatHourMoneyMessage getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_io_union_log_common_proto_StatHourMoneyMessage_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_io_union_log_common_proto_StatHourMoneyMessage_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\023StatHourMoney.proto\022\031io.union.log.comm" +
                        "on.proto\"\327\003\n\024StatHourMoneyMessage\022\n\n\002id\030" +
                        "\001 \001(\004\022\013\n\003uid\030\002 \001(\004\022\016\n\006siteid\030\003 \001(\004\022\016\n\006pl" +
                        "anid\030\004 \001(\004\022\020\n\010add_time\030\005 \001(\004\022\r\n\005hour0\030\006 " +
                        "\001(\001\022\r\n\005hour1\030\007 \001(\001\022\r\n\005hour2\030\010 \001(\001\022\r\n\005hou" +
                        "r3\030\t \001(\001\022\r\n\005hour4\030\n \001(\001\022\r\n\005hour5\030\013 \001(\001\022\r" +
                        "\n\005hour6\030\014 \001(\001\022\r\n\005hour7\030\r \001(\001\022\r\n\005hour8\030\016 " +
                        "\001(\001\022\r\n\005hour9\030\017 \001(\001\022\016\n\006hour10\030\020 \001(\001\022\016\n\006ho" +
                        "ur11\030\021 \001(\001\022\016\n\006hour12\030\022 \001(\001\022\016\n\006hour13\030\023 \001" +
                        "(\001\022\016\n\006hour14\030\024 \001(\001\022\016\n\006hour15\030\025 \001(\001\022\016\n\006ho",
                "ur16\030\026 \001(\001\022\016\n\006hour17\030\027 \001(\001\022\016\n\006hour18\030\030 \001" +
                        "(\001\022\016\n\006hour19\030\031 \001(\001\022\016\n\006hour20\030\032 \001(\001\022\016\n\006ho" +
                        "ur21\030\033 \001(\001\022\016\n\006hour22\030\034 \001(\001\022\016\n\006hour23\030\035 \001" +
                        "(\001B/\n\031io.union.log.common.protoB\022StatHou" +
                        "rMoneyProtob\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_io_union_log_common_proto_StatHourMoneyMessage_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_io_union_log_common_proto_StatHourMoneyMessage_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_io_union_log_common_proto_StatHourMoneyMessage_descriptor,
                new java.lang.String[]{"Id", "Uid", "Siteid", "Planid", "AddTime", "Hour0", "Hour1", "Hour2", "Hour3", "Hour4", "Hour5", "Hour6", "Hour7", "Hour8", "Hour9", "Hour10", "Hour11", "Hour12", "Hour13", "Hour14", "Hour15", "Hour16", "Hour17", "Hour18", "Hour19", "Hour20", "Hour21", "Hour22", "Hour23",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
