// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StatHourIp.proto

package io.union.log.common.proto;

public final class StatHourIpProto {
    private StatHourIpProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface StatHourIpMessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:io.union.log.common.proto.StatHourIpMessage)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>uint64 id = 1;</code>
         */
        long getId();

        /**
         * <code>uint64 uid = 2;</code>
         */
        long getUid();

        /**
         * <code>uint64 siteid = 3;</code>
         */
        long getSiteid();

        /**
         * <code>uint64 planid = 4;</code>
         */
        long getPlanid();

        /**
         * <code>uint64 add_time = 5;</code>
         */
        long getAddTime();

        /**
         * <code>uint64 hour0 = 6;</code>
         */
        long getHour0();

        /**
         * <code>uint64 hour1 = 7;</code>
         */
        long getHour1();

        /**
         * <code>uint64 hour2 = 8;</code>
         */
        long getHour2();

        /**
         * <code>uint64 hour3 = 9;</code>
         */
        long getHour3();

        /**
         * <code>uint64 hour4 = 10;</code>
         */
        long getHour4();

        /**
         * <code>uint64 hour5 = 11;</code>
         */
        long getHour5();

        /**
         * <code>uint64 hour6 = 12;</code>
         */
        long getHour6();

        /**
         * <code>uint64 hour7 = 13;</code>
         */
        long getHour7();

        /**
         * <code>uint64 hour8 = 14;</code>
         */
        long getHour8();

        /**
         * <code>uint64 hour9 = 15;</code>
         */
        long getHour9();

        /**
         * <code>uint64 hour10 = 16;</code>
         */
        long getHour10();

        /**
         * <code>uint64 hour11 = 17;</code>
         */
        long getHour11();

        /**
         * <code>uint64 hour12 = 18;</code>
         */
        long getHour12();

        /**
         * <code>uint64 hour13 = 19;</code>
         */
        long getHour13();

        /**
         * <code>uint64 hour14 = 20;</code>
         */
        long getHour14();

        /**
         * <code>uint64 hour15 = 21;</code>
         */
        long getHour15();

        /**
         * <code>uint64 hour16 = 22;</code>
         */
        long getHour16();

        /**
         * <code>uint64 hour17 = 23;</code>
         */
        long getHour17();

        /**
         * <code>uint64 hour18 = 24;</code>
         */
        long getHour18();

        /**
         * <code>uint64 hour19 = 25;</code>
         */
        long getHour19();

        /**
         * <code>uint64 hour20 = 26;</code>
         */
        long getHour20();

        /**
         * <code>uint64 hour21 = 27;</code>
         */
        long getHour21();

        /**
         * <code>uint64 hour22 = 28;</code>
         */
        long getHour22();

        /**
         * <code>uint64 hour23 = 29;</code>
         */
        long getHour23();
    }

    /**
     * Protobuf type {@code io.union.log.common.proto.StatHourIpMessage}
     */
    public static final class StatHourIpMessage extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:io.union.log.common.proto.StatHourIpMessage)
            StatHourIpMessageOrBuilder {
        // Use StatHourIpMessage.newBuilder() to construct.
        private StatHourIpMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private StatHourIpMessage() {
            id_ = 0L;
            uid_ = 0L;
            siteid_ = 0L;
            planid_ = 0L;
            addTime_ = 0L;
            hour0_ = 0L;
            hour1_ = 0L;
            hour2_ = 0L;
            hour3_ = 0L;
            hour4_ = 0L;
            hour5_ = 0L;
            hour6_ = 0L;
            hour7_ = 0L;
            hour8_ = 0L;
            hour9_ = 0L;
            hour10_ = 0L;
            hour11_ = 0L;
            hour12_ = 0L;
            hour13_ = 0L;
            hour14_ = 0L;
            hour15_ = 0L;
            hour16_ = 0L;
            hour17_ = 0L;
            hour18_ = 0L;
            hour19_ = 0L;
            hour20_ = 0L;
            hour21_ = 0L;
            hour22_ = 0L;
            hour23_ = 0L;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private StatHourIpMessage(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            id_ = input.readUInt64();
                            break;
                        }
                        case 16: {

                            uid_ = input.readUInt64();
                            break;
                        }
                        case 24: {

                            siteid_ = input.readUInt64();
                            break;
                        }
                        case 32: {

                            planid_ = input.readUInt64();
                            break;
                        }
                        case 40: {

                            addTime_ = input.readUInt64();
                            break;
                        }
                        case 48: {

                            hour0_ = input.readUInt64();
                            break;
                        }
                        case 56: {

                            hour1_ = input.readUInt64();
                            break;
                        }
                        case 64: {

                            hour2_ = input.readUInt64();
                            break;
                        }
                        case 72: {

                            hour3_ = input.readUInt64();
                            break;
                        }
                        case 80: {

                            hour4_ = input.readUInt64();
                            break;
                        }
                        case 88: {

                            hour5_ = input.readUInt64();
                            break;
                        }
                        case 96: {

                            hour6_ = input.readUInt64();
                            break;
                        }
                        case 104: {

                            hour7_ = input.readUInt64();
                            break;
                        }
                        case 112: {

                            hour8_ = input.readUInt64();
                            break;
                        }
                        case 120: {

                            hour9_ = input.readUInt64();
                            break;
                        }
                        case 128: {

                            hour10_ = input.readUInt64();
                            break;
                        }
                        case 136: {

                            hour11_ = input.readUInt64();
                            break;
                        }
                        case 144: {

                            hour12_ = input.readUInt64();
                            break;
                        }
                        case 152: {

                            hour13_ = input.readUInt64();
                            break;
                        }
                        case 160: {

                            hour14_ = input.readUInt64();
                            break;
                        }
                        case 168: {

                            hour15_ = input.readUInt64();
                            break;
                        }
                        case 176: {

                            hour16_ = input.readUInt64();
                            break;
                        }
                        case 184: {

                            hour17_ = input.readUInt64();
                            break;
                        }
                        case 192: {

                            hour18_ = input.readUInt64();
                            break;
                        }
                        case 200: {

                            hour19_ = input.readUInt64();
                            break;
                        }
                        case 208: {

                            hour20_ = input.readUInt64();
                            break;
                        }
                        case 216: {

                            hour21_ = input.readUInt64();
                            break;
                        }
                        case 224: {

                            hour22_ = input.readUInt64();
                            break;
                        }
                        case 232: {

                            hour23_ = input.readUInt64();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return io.union.log.common.proto.StatHourIpProto.internal_static_io_union_log_common_proto_StatHourIpMessage_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return io.union.log.common.proto.StatHourIpProto.internal_static_io_union_log_common_proto_StatHourIpMessage_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            io.union.log.common.proto.StatHourIpProto.StatHourIpMessage.class, io.union.log.common.proto.StatHourIpProto.StatHourIpMessage.Builder.class);
        }

        public static final int ID_FIELD_NUMBER = 1;
        private long id_;

        /**
         * <code>uint64 id = 1;</code>
         */
        public long getId() {
            return id_;
        }

        public static final int UID_FIELD_NUMBER = 2;
        private long uid_;

        /**
         * <code>uint64 uid = 2;</code>
         */
        public long getUid() {
            return uid_;
        }

        public static final int SITEID_FIELD_NUMBER = 3;
        private long siteid_;

        /**
         * <code>uint64 siteid = 3;</code>
         */
        public long getSiteid() {
            return siteid_;
        }

        public static final int PLANID_FIELD_NUMBER = 4;
        private long planid_;

        /**
         * <code>uint64 planid = 4;</code>
         */
        public long getPlanid() {
            return planid_;
        }

        public static final int ADD_TIME_FIELD_NUMBER = 5;
        private long addTime_;

        /**
         * <code>uint64 add_time = 5;</code>
         */
        public long getAddTime() {
            return addTime_;
        }

        public static final int HOUR0_FIELD_NUMBER = 6;
        private long hour0_;

        /**
         * <code>uint64 hour0 = 6;</code>
         */
        public long getHour0() {
            return hour0_;
        }

        public static final int HOUR1_FIELD_NUMBER = 7;
        private long hour1_;

        /**
         * <code>uint64 hour1 = 7;</code>
         */
        public long getHour1() {
            return hour1_;
        }

        public static final int HOUR2_FIELD_NUMBER = 8;
        private long hour2_;

        /**
         * <code>uint64 hour2 = 8;</code>
         */
        public long getHour2() {
            return hour2_;
        }

        public static final int HOUR3_FIELD_NUMBER = 9;
        private long hour3_;

        /**
         * <code>uint64 hour3 = 9;</code>
         */
        public long getHour3() {
            return hour3_;
        }

        public static final int HOUR4_FIELD_NUMBER = 10;
        private long hour4_;

        /**
         * <code>uint64 hour4 = 10;</code>
         */
        public long getHour4() {
            return hour4_;
        }

        public static final int HOUR5_FIELD_NUMBER = 11;
        private long hour5_;

        /**
         * <code>uint64 hour5 = 11;</code>
         */
        public long getHour5() {
            return hour5_;
        }

        public static final int HOUR6_FIELD_NUMBER = 12;
        private long hour6_;

        /**
         * <code>uint64 hour6 = 12;</code>
         */
        public long getHour6() {
            return hour6_;
        }

        public static final int HOUR7_FIELD_NUMBER = 13;
        private long hour7_;

        /**
         * <code>uint64 hour7 = 13;</code>
         */
        public long getHour7() {
            return hour7_;
        }

        public static final int HOUR8_FIELD_NUMBER = 14;
        private long hour8_;

        /**
         * <code>uint64 hour8 = 14;</code>
         */
        public long getHour8() {
            return hour8_;
        }

        public static final int HOUR9_FIELD_NUMBER = 15;
        private long hour9_;

        /**
         * <code>uint64 hour9 = 15;</code>
         */
        public long getHour9() {
            return hour9_;
        }

        public static final int HOUR10_FIELD_NUMBER = 16;
        private long hour10_;

        /**
         * <code>uint64 hour10 = 16;</code>
         */
        public long getHour10() {
            return hour10_;
        }

        public static final int HOUR11_FIELD_NUMBER = 17;
        private long hour11_;

        /**
         * <code>uint64 hour11 = 17;</code>
         */
        public long getHour11() {
            return hour11_;
        }

        public static final int HOUR12_FIELD_NUMBER = 18;
        private long hour12_;

        /**
         * <code>uint64 hour12 = 18;</code>
         */
        public long getHour12() {
            return hour12_;
        }

        public static final int HOUR13_FIELD_NUMBER = 19;
        private long hour13_;

        /**
         * <code>uint64 hour13 = 19;</code>
         */
        public long getHour13() {
            return hour13_;
        }

        public static final int HOUR14_FIELD_NUMBER = 20;
        private long hour14_;

        /**
         * <code>uint64 hour14 = 20;</code>
         */
        public long getHour14() {
            return hour14_;
        }

        public static final int HOUR15_FIELD_NUMBER = 21;
        private long hour15_;

        /**
         * <code>uint64 hour15 = 21;</code>
         */
        public long getHour15() {
            return hour15_;
        }

        public static final int HOUR16_FIELD_NUMBER = 22;
        private long hour16_;

        /**
         * <code>uint64 hour16 = 22;</code>
         */
        public long getHour16() {
            return hour16_;
        }

        public static final int HOUR17_FIELD_NUMBER = 23;
        private long hour17_;

        /**
         * <code>uint64 hour17 = 23;</code>
         */
        public long getHour17() {
            return hour17_;
        }

        public static final int HOUR18_FIELD_NUMBER = 24;
        private long hour18_;

        /**
         * <code>uint64 hour18 = 24;</code>
         */
        public long getHour18() {
            return hour18_;
        }

        public static final int HOUR19_FIELD_NUMBER = 25;
        private long hour19_;

        /**
         * <code>uint64 hour19 = 25;</code>
         */
        public long getHour19() {
            return hour19_;
        }

        public static final int HOUR20_FIELD_NUMBER = 26;
        private long hour20_;

        /**
         * <code>uint64 hour20 = 26;</code>
         */
        public long getHour20() {
            return hour20_;
        }

        public static final int HOUR21_FIELD_NUMBER = 27;
        private long hour21_;

        /**
         * <code>uint64 hour21 = 27;</code>
         */
        public long getHour21() {
            return hour21_;
        }

        public static final int HOUR22_FIELD_NUMBER = 28;
        private long hour22_;

        /**
         * <code>uint64 hour22 = 28;</code>
         */
        public long getHour22() {
            return hour22_;
        }

        public static final int HOUR23_FIELD_NUMBER = 29;
        private long hour23_;

        /**
         * <code>uint64 hour23 = 29;</code>
         */
        public long getHour23() {
            return hour23_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (id_ != 0L) {
                output.writeUInt64(1, id_);
            }
            if (uid_ != 0L) {
                output.writeUInt64(2, uid_);
            }
            if (siteid_ != 0L) {
                output.writeUInt64(3, siteid_);
            }
            if (planid_ != 0L) {
                output.writeUInt64(4, planid_);
            }
            if (addTime_ != 0L) {
                output.writeUInt64(5, addTime_);
            }
            if (hour0_ != 0L) {
                output.writeUInt64(6, hour0_);
            }
            if (hour1_ != 0L) {
                output.writeUInt64(7, hour1_);
            }
            if (hour2_ != 0L) {
                output.writeUInt64(8, hour2_);
            }
            if (hour3_ != 0L) {
                output.writeUInt64(9, hour3_);
            }
            if (hour4_ != 0L) {
                output.writeUInt64(10, hour4_);
            }
            if (hour5_ != 0L) {
                output.writeUInt64(11, hour5_);
            }
            if (hour6_ != 0L) {
                output.writeUInt64(12, hour6_);
            }
            if (hour7_ != 0L) {
                output.writeUInt64(13, hour7_);
            }
            if (hour8_ != 0L) {
                output.writeUInt64(14, hour8_);
            }
            if (hour9_ != 0L) {
                output.writeUInt64(15, hour9_);
            }
            if (hour10_ != 0L) {
                output.writeUInt64(16, hour10_);
            }
            if (hour11_ != 0L) {
                output.writeUInt64(17, hour11_);
            }
            if (hour12_ != 0L) {
                output.writeUInt64(18, hour12_);
            }
            if (hour13_ != 0L) {
                output.writeUInt64(19, hour13_);
            }
            if (hour14_ != 0L) {
                output.writeUInt64(20, hour14_);
            }
            if (hour15_ != 0L) {
                output.writeUInt64(21, hour15_);
            }
            if (hour16_ != 0L) {
                output.writeUInt64(22, hour16_);
            }
            if (hour17_ != 0L) {
                output.writeUInt64(23, hour17_);
            }
            if (hour18_ != 0L) {
                output.writeUInt64(24, hour18_);
            }
            if (hour19_ != 0L) {
                output.writeUInt64(25, hour19_);
            }
            if (hour20_ != 0L) {
                output.writeUInt64(26, hour20_);
            }
            if (hour21_ != 0L) {
                output.writeUInt64(27, hour21_);
            }
            if (hour22_ != 0L) {
                output.writeUInt64(28, hour22_);
            }
            if (hour23_ != 0L) {
                output.writeUInt64(29, hour23_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (id_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(1, id_);
            }
            if (uid_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(2, uid_);
            }
            if (siteid_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(3, siteid_);
            }
            if (planid_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(4, planid_);
            }
            if (addTime_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(5, addTime_);
            }
            if (hour0_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(6, hour0_);
            }
            if (hour1_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(7, hour1_);
            }
            if (hour2_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(8, hour2_);
            }
            if (hour3_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(9, hour3_);
            }
            if (hour4_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(10, hour4_);
            }
            if (hour5_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(11, hour5_);
            }
            if (hour6_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(12, hour6_);
            }
            if (hour7_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(13, hour7_);
            }
            if (hour8_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(14, hour8_);
            }
            if (hour9_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(15, hour9_);
            }
            if (hour10_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(16, hour10_);
            }
            if (hour11_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(17, hour11_);
            }
            if (hour12_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(18, hour12_);
            }
            if (hour13_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(19, hour13_);
            }
            if (hour14_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(20, hour14_);
            }
            if (hour15_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(21, hour15_);
            }
            if (hour16_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(22, hour16_);
            }
            if (hour17_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(23, hour17_);
            }
            if (hour18_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(24, hour18_);
            }
            if (hour19_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(25, hour19_);
            }
            if (hour20_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(26, hour20_);
            }
            if (hour21_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(27, hour21_);
            }
            if (hour22_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(28, hour22_);
            }
            if (hour23_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(29, hour23_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof io.union.log.common.proto.StatHourIpProto.StatHourIpMessage)) {
                return super.equals(obj);
            }
            io.union.log.common.proto.StatHourIpProto.StatHourIpMessage other = (io.union.log.common.proto.StatHourIpProto.StatHourIpMessage) obj;

            boolean result = true;
            result = result && (getId()
                    == other.getId());
            result = result && (getUid()
                    == other.getUid());
            result = result && (getSiteid()
                    == other.getSiteid());
            result = result && (getPlanid()
                    == other.getPlanid());
            result = result && (getAddTime()
                    == other.getAddTime());
            result = result && (getHour0()
                    == other.getHour0());
            result = result && (getHour1()
                    == other.getHour1());
            result = result && (getHour2()
                    == other.getHour2());
            result = result && (getHour3()
                    == other.getHour3());
            result = result && (getHour4()
                    == other.getHour4());
            result = result && (getHour5()
                    == other.getHour5());
            result = result && (getHour6()
                    == other.getHour6());
            result = result && (getHour7()
                    == other.getHour7());
            result = result && (getHour8()
                    == other.getHour8());
            result = result && (getHour9()
                    == other.getHour9());
            result = result && (getHour10()
                    == other.getHour10());
            result = result && (getHour11()
                    == other.getHour11());
            result = result && (getHour12()
                    == other.getHour12());
            result = result && (getHour13()
                    == other.getHour13());
            result = result && (getHour14()
                    == other.getHour14());
            result = result && (getHour15()
                    == other.getHour15());
            result = result && (getHour16()
                    == other.getHour16());
            result = result && (getHour17()
                    == other.getHour17());
            result = result && (getHour18()
                    == other.getHour18());
            result = result && (getHour19()
                    == other.getHour19());
            result = result && (getHour20()
                    == other.getHour20());
            result = result && (getHour21()
                    == other.getHour21());
            result = result && (getHour22()
                    == other.getHour22());
            result = result && (getHour23()
                    == other.getHour23());
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getId());
            hash = (37 * hash) + UID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getUid());
            hash = (37 * hash) + SITEID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getSiteid());
            hash = (37 * hash) + PLANID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getPlanid());
            hash = (37 * hash) + ADD_TIME_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getAddTime());
            hash = (37 * hash) + HOUR0_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getHour0());
            hash = (37 * hash) + HOUR1_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getHour1());
            hash = (37 * hash) + HOUR2_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getHour2());
            hash = (37 * hash) + HOUR3_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getHour3());
            hash = (37 * hash) + HOUR4_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getHour4());
            hash = (37 * hash) + HOUR5_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getHour5());
            hash = (37 * hash) + HOUR6_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getHour6());
            hash = (37 * hash) + HOUR7_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getHour7());
            hash = (37 * hash) + HOUR8_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getHour8());
            hash = (37 * hash) + HOUR9_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getHour9());
            hash = (37 * hash) + HOUR10_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getHour10());
            hash = (37 * hash) + HOUR11_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getHour11());
            hash = (37 * hash) + HOUR12_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getHour12());
            hash = (37 * hash) + HOUR13_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getHour13());
            hash = (37 * hash) + HOUR14_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getHour14());
            hash = (37 * hash) + HOUR15_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getHour15());
            hash = (37 * hash) + HOUR16_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getHour16());
            hash = (37 * hash) + HOUR17_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getHour17());
            hash = (37 * hash) + HOUR18_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getHour18());
            hash = (37 * hash) + HOUR19_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getHour19());
            hash = (37 * hash) + HOUR20_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getHour20());
            hash = (37 * hash) + HOUR21_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getHour21());
            hash = (37 * hash) + HOUR22_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getHour22());
            hash = (37 * hash) + HOUR23_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getHour23());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static io.union.log.common.proto.StatHourIpProto.StatHourIpMessage parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.union.log.common.proto.StatHourIpProto.StatHourIpMessage parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.union.log.common.proto.StatHourIpProto.StatHourIpMessage parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.union.log.common.proto.StatHourIpProto.StatHourIpMessage parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.union.log.common.proto.StatHourIpProto.StatHourIpMessage parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.union.log.common.proto.StatHourIpProto.StatHourIpMessage parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.union.log.common.proto.StatHourIpProto.StatHourIpMessage parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static io.union.log.common.proto.StatHourIpProto.StatHourIpMessage parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static io.union.log.common.proto.StatHourIpProto.StatHourIpMessage parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static io.union.log.common.proto.StatHourIpProto.StatHourIpMessage parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static io.union.log.common.proto.StatHourIpProto.StatHourIpMessage parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static io.union.log.common.proto.StatHourIpProto.StatHourIpMessage parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(io.union.log.common.proto.StatHourIpProto.StatHourIpMessage prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code io.union.log.common.proto.StatHourIpMessage}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:io.union.log.common.proto.StatHourIpMessage)
                io.union.log.common.proto.StatHourIpProto.StatHourIpMessageOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return io.union.log.common.proto.StatHourIpProto.internal_static_io_union_log_common_proto_StatHourIpMessage_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return io.union.log.common.proto.StatHourIpProto.internal_static_io_union_log_common_proto_StatHourIpMessage_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                io.union.log.common.proto.StatHourIpProto.StatHourIpMessage.class, io.union.log.common.proto.StatHourIpProto.StatHourIpMessage.Builder.class);
            }

            // Construct using io.union.log.common.proto.StatHourIpProto.StatHourIpMessage.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                id_ = 0L;

                uid_ = 0L;

                siteid_ = 0L;

                planid_ = 0L;

                addTime_ = 0L;

                hour0_ = 0L;

                hour1_ = 0L;

                hour2_ = 0L;

                hour3_ = 0L;

                hour4_ = 0L;

                hour5_ = 0L;

                hour6_ = 0L;

                hour7_ = 0L;

                hour8_ = 0L;

                hour9_ = 0L;

                hour10_ = 0L;

                hour11_ = 0L;

                hour12_ = 0L;

                hour13_ = 0L;

                hour14_ = 0L;

                hour15_ = 0L;

                hour16_ = 0L;

                hour17_ = 0L;

                hour18_ = 0L;

                hour19_ = 0L;

                hour20_ = 0L;

                hour21_ = 0L;

                hour22_ = 0L;

                hour23_ = 0L;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return io.union.log.common.proto.StatHourIpProto.internal_static_io_union_log_common_proto_StatHourIpMessage_descriptor;
            }

            public io.union.log.common.proto.StatHourIpProto.StatHourIpMessage getDefaultInstanceForType() {
                return io.union.log.common.proto.StatHourIpProto.StatHourIpMessage.getDefaultInstance();
            }

            public io.union.log.common.proto.StatHourIpProto.StatHourIpMessage build() {
                io.union.log.common.proto.StatHourIpProto.StatHourIpMessage result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public io.union.log.common.proto.StatHourIpProto.StatHourIpMessage buildPartial() {
                io.union.log.common.proto.StatHourIpProto.StatHourIpMessage result = new io.union.log.common.proto.StatHourIpProto.StatHourIpMessage(this);
                result.id_ = id_;
                result.uid_ = uid_;
                result.siteid_ = siteid_;
                result.planid_ = planid_;
                result.addTime_ = addTime_;
                result.hour0_ = hour0_;
                result.hour1_ = hour1_;
                result.hour2_ = hour2_;
                result.hour3_ = hour3_;
                result.hour4_ = hour4_;
                result.hour5_ = hour5_;
                result.hour6_ = hour6_;
                result.hour7_ = hour7_;
                result.hour8_ = hour8_;
                result.hour9_ = hour9_;
                result.hour10_ = hour10_;
                result.hour11_ = hour11_;
                result.hour12_ = hour12_;
                result.hour13_ = hour13_;
                result.hour14_ = hour14_;
                result.hour15_ = hour15_;
                result.hour16_ = hour16_;
                result.hour17_ = hour17_;
                result.hour18_ = hour18_;
                result.hour19_ = hour19_;
                result.hour20_ = hour20_;
                result.hour21_ = hour21_;
                result.hour22_ = hour22_;
                result.hour23_ = hour23_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof io.union.log.common.proto.StatHourIpProto.StatHourIpMessage) {
                    return mergeFrom((io.union.log.common.proto.StatHourIpProto.StatHourIpMessage) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(io.union.log.common.proto.StatHourIpProto.StatHourIpMessage other) {
                if (other == io.union.log.common.proto.StatHourIpProto.StatHourIpMessage.getDefaultInstance())
                    return this;
                if (other.getId() != 0L) {
                    setId(other.getId());
                }
                if (other.getUid() != 0L) {
                    setUid(other.getUid());
                }
                if (other.getSiteid() != 0L) {
                    setSiteid(other.getSiteid());
                }
                if (other.getPlanid() != 0L) {
                    setPlanid(other.getPlanid());
                }
                if (other.getAddTime() != 0L) {
                    setAddTime(other.getAddTime());
                }
                if (other.getHour0() != 0L) {
                    setHour0(other.getHour0());
                }
                if (other.getHour1() != 0L) {
                    setHour1(other.getHour1());
                }
                if (other.getHour2() != 0L) {
                    setHour2(other.getHour2());
                }
                if (other.getHour3() != 0L) {
                    setHour3(other.getHour3());
                }
                if (other.getHour4() != 0L) {
                    setHour4(other.getHour4());
                }
                if (other.getHour5() != 0L) {
                    setHour5(other.getHour5());
                }
                if (other.getHour6() != 0L) {
                    setHour6(other.getHour6());
                }
                if (other.getHour7() != 0L) {
                    setHour7(other.getHour7());
                }
                if (other.getHour8() != 0L) {
                    setHour8(other.getHour8());
                }
                if (other.getHour9() != 0L) {
                    setHour9(other.getHour9());
                }
                if (other.getHour10() != 0L) {
                    setHour10(other.getHour10());
                }
                if (other.getHour11() != 0L) {
                    setHour11(other.getHour11());
                }
                if (other.getHour12() != 0L) {
                    setHour12(other.getHour12());
                }
                if (other.getHour13() != 0L) {
                    setHour13(other.getHour13());
                }
                if (other.getHour14() != 0L) {
                    setHour14(other.getHour14());
                }
                if (other.getHour15() != 0L) {
                    setHour15(other.getHour15());
                }
                if (other.getHour16() != 0L) {
                    setHour16(other.getHour16());
                }
                if (other.getHour17() != 0L) {
                    setHour17(other.getHour17());
                }
                if (other.getHour18() != 0L) {
                    setHour18(other.getHour18());
                }
                if (other.getHour19() != 0L) {
                    setHour19(other.getHour19());
                }
                if (other.getHour20() != 0L) {
                    setHour20(other.getHour20());
                }
                if (other.getHour21() != 0L) {
                    setHour21(other.getHour21());
                }
                if (other.getHour22() != 0L) {
                    setHour22(other.getHour22());
                }
                if (other.getHour23() != 0L) {
                    setHour23(other.getHour23());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                io.union.log.common.proto.StatHourIpProto.StatHourIpMessage parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (io.union.log.common.proto.StatHourIpProto.StatHourIpMessage) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private long id_;

            /**
             * <code>uint64 id = 1;</code>
             */
            public long getId() {
                return id_;
            }

            /**
             * <code>uint64 id = 1;</code>
             */
            public Builder setId(long value) {

                id_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 id = 1;</code>
             */
            public Builder clearId() {

                id_ = 0L;
                onChanged();
                return this;
            }

            private long uid_;

            /**
             * <code>uint64 uid = 2;</code>
             */
            public long getUid() {
                return uid_;
            }

            /**
             * <code>uint64 uid = 2;</code>
             */
            public Builder setUid(long value) {

                uid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 uid = 2;</code>
             */
            public Builder clearUid() {

                uid_ = 0L;
                onChanged();
                return this;
            }

            private long siteid_;

            /**
             * <code>uint64 siteid = 3;</code>
             */
            public long getSiteid() {
                return siteid_;
            }

            /**
             * <code>uint64 siteid = 3;</code>
             */
            public Builder setSiteid(long value) {

                siteid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 siteid = 3;</code>
             */
            public Builder clearSiteid() {

                siteid_ = 0L;
                onChanged();
                return this;
            }

            private long planid_;

            /**
             * <code>uint64 planid = 4;</code>
             */
            public long getPlanid() {
                return planid_;
            }

            /**
             * <code>uint64 planid = 4;</code>
             */
            public Builder setPlanid(long value) {

                planid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 planid = 4;</code>
             */
            public Builder clearPlanid() {

                planid_ = 0L;
                onChanged();
                return this;
            }

            private long addTime_;

            /**
             * <code>uint64 add_time = 5;</code>
             */
            public long getAddTime() {
                return addTime_;
            }

            /**
             * <code>uint64 add_time = 5;</code>
             */
            public Builder setAddTime(long value) {

                addTime_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 add_time = 5;</code>
             */
            public Builder clearAddTime() {

                addTime_ = 0L;
                onChanged();
                return this;
            }

            private long hour0_;

            /**
             * <code>uint64 hour0 = 6;</code>
             */
            public long getHour0() {
                return hour0_;
            }

            /**
             * <code>uint64 hour0 = 6;</code>
             */
            public Builder setHour0(long value) {

                hour0_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 hour0 = 6;</code>
             */
            public Builder clearHour0() {

                hour0_ = 0L;
                onChanged();
                return this;
            }

            private long hour1_;

            /**
             * <code>uint64 hour1 = 7;</code>
             */
            public long getHour1() {
                return hour1_;
            }

            /**
             * <code>uint64 hour1 = 7;</code>
             */
            public Builder setHour1(long value) {

                hour1_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 hour1 = 7;</code>
             */
            public Builder clearHour1() {

                hour1_ = 0L;
                onChanged();
                return this;
            }

            private long hour2_;

            /**
             * <code>uint64 hour2 = 8;</code>
             */
            public long getHour2() {
                return hour2_;
            }

            /**
             * <code>uint64 hour2 = 8;</code>
             */
            public Builder setHour2(long value) {

                hour2_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 hour2 = 8;</code>
             */
            public Builder clearHour2() {

                hour2_ = 0L;
                onChanged();
                return this;
            }

            private long hour3_;

            /**
             * <code>uint64 hour3 = 9;</code>
             */
            public long getHour3() {
                return hour3_;
            }

            /**
             * <code>uint64 hour3 = 9;</code>
             */
            public Builder setHour3(long value) {

                hour3_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 hour3 = 9;</code>
             */
            public Builder clearHour3() {

                hour3_ = 0L;
                onChanged();
                return this;
            }

            private long hour4_;

            /**
             * <code>uint64 hour4 = 10;</code>
             */
            public long getHour4() {
                return hour4_;
            }

            /**
             * <code>uint64 hour4 = 10;</code>
             */
            public Builder setHour4(long value) {

                hour4_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 hour4 = 10;</code>
             */
            public Builder clearHour4() {

                hour4_ = 0L;
                onChanged();
                return this;
            }

            private long hour5_;

            /**
             * <code>uint64 hour5 = 11;</code>
             */
            public long getHour5() {
                return hour5_;
            }

            /**
             * <code>uint64 hour5 = 11;</code>
             */
            public Builder setHour5(long value) {

                hour5_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 hour5 = 11;</code>
             */
            public Builder clearHour5() {

                hour5_ = 0L;
                onChanged();
                return this;
            }

            private long hour6_;

            /**
             * <code>uint64 hour6 = 12;</code>
             */
            public long getHour6() {
                return hour6_;
            }

            /**
             * <code>uint64 hour6 = 12;</code>
             */
            public Builder setHour6(long value) {

                hour6_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 hour6 = 12;</code>
             */
            public Builder clearHour6() {

                hour6_ = 0L;
                onChanged();
                return this;
            }

            private long hour7_;

            /**
             * <code>uint64 hour7 = 13;</code>
             */
            public long getHour7() {
                return hour7_;
            }

            /**
             * <code>uint64 hour7 = 13;</code>
             */
            public Builder setHour7(long value) {

                hour7_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 hour7 = 13;</code>
             */
            public Builder clearHour7() {

                hour7_ = 0L;
                onChanged();
                return this;
            }

            private long hour8_;

            /**
             * <code>uint64 hour8 = 14;</code>
             */
            public long getHour8() {
                return hour8_;
            }

            /**
             * <code>uint64 hour8 = 14;</code>
             */
            public Builder setHour8(long value) {

                hour8_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 hour8 = 14;</code>
             */
            public Builder clearHour8() {

                hour8_ = 0L;
                onChanged();
                return this;
            }

            private long hour9_;

            /**
             * <code>uint64 hour9 = 15;</code>
             */
            public long getHour9() {
                return hour9_;
            }

            /**
             * <code>uint64 hour9 = 15;</code>
             */
            public Builder setHour9(long value) {

                hour9_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 hour9 = 15;</code>
             */
            public Builder clearHour9() {

                hour9_ = 0L;
                onChanged();
                return this;
            }

            private long hour10_;

            /**
             * <code>uint64 hour10 = 16;</code>
             */
            public long getHour10() {
                return hour10_;
            }

            /**
             * <code>uint64 hour10 = 16;</code>
             */
            public Builder setHour10(long value) {

                hour10_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 hour10 = 16;</code>
             */
            public Builder clearHour10() {

                hour10_ = 0L;
                onChanged();
                return this;
            }

            private long hour11_;

            /**
             * <code>uint64 hour11 = 17;</code>
             */
            public long getHour11() {
                return hour11_;
            }

            /**
             * <code>uint64 hour11 = 17;</code>
             */
            public Builder setHour11(long value) {

                hour11_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 hour11 = 17;</code>
             */
            public Builder clearHour11() {

                hour11_ = 0L;
                onChanged();
                return this;
            }

            private long hour12_;

            /**
             * <code>uint64 hour12 = 18;</code>
             */
            public long getHour12() {
                return hour12_;
            }

            /**
             * <code>uint64 hour12 = 18;</code>
             */
            public Builder setHour12(long value) {

                hour12_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 hour12 = 18;</code>
             */
            public Builder clearHour12() {

                hour12_ = 0L;
                onChanged();
                return this;
            }

            private long hour13_;

            /**
             * <code>uint64 hour13 = 19;</code>
             */
            public long getHour13() {
                return hour13_;
            }

            /**
             * <code>uint64 hour13 = 19;</code>
             */
            public Builder setHour13(long value) {

                hour13_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 hour13 = 19;</code>
             */
            public Builder clearHour13() {

                hour13_ = 0L;
                onChanged();
                return this;
            }

            private long hour14_;

            /**
             * <code>uint64 hour14 = 20;</code>
             */
            public long getHour14() {
                return hour14_;
            }

            /**
             * <code>uint64 hour14 = 20;</code>
             */
            public Builder setHour14(long value) {

                hour14_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 hour14 = 20;</code>
             */
            public Builder clearHour14() {

                hour14_ = 0L;
                onChanged();
                return this;
            }

            private long hour15_;

            /**
             * <code>uint64 hour15 = 21;</code>
             */
            public long getHour15() {
                return hour15_;
            }

            /**
             * <code>uint64 hour15 = 21;</code>
             */
            public Builder setHour15(long value) {

                hour15_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 hour15 = 21;</code>
             */
            public Builder clearHour15() {

                hour15_ = 0L;
                onChanged();
                return this;
            }

            private long hour16_;

            /**
             * <code>uint64 hour16 = 22;</code>
             */
            public long getHour16() {
                return hour16_;
            }

            /**
             * <code>uint64 hour16 = 22;</code>
             */
            public Builder setHour16(long value) {

                hour16_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 hour16 = 22;</code>
             */
            public Builder clearHour16() {

                hour16_ = 0L;
                onChanged();
                return this;
            }

            private long hour17_;

            /**
             * <code>uint64 hour17 = 23;</code>
             */
            public long getHour17() {
                return hour17_;
            }

            /**
             * <code>uint64 hour17 = 23;</code>
             */
            public Builder setHour17(long value) {

                hour17_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 hour17 = 23;</code>
             */
            public Builder clearHour17() {

                hour17_ = 0L;
                onChanged();
                return this;
            }

            private long hour18_;

            /**
             * <code>uint64 hour18 = 24;</code>
             */
            public long getHour18() {
                return hour18_;
            }

            /**
             * <code>uint64 hour18 = 24;</code>
             */
            public Builder setHour18(long value) {

                hour18_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 hour18 = 24;</code>
             */
            public Builder clearHour18() {

                hour18_ = 0L;
                onChanged();
                return this;
            }

            private long hour19_;

            /**
             * <code>uint64 hour19 = 25;</code>
             */
            public long getHour19() {
                return hour19_;
            }

            /**
             * <code>uint64 hour19 = 25;</code>
             */
            public Builder setHour19(long value) {

                hour19_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 hour19 = 25;</code>
             */
            public Builder clearHour19() {

                hour19_ = 0L;
                onChanged();
                return this;
            }

            private long hour20_;

            /**
             * <code>uint64 hour20 = 26;</code>
             */
            public long getHour20() {
                return hour20_;
            }

            /**
             * <code>uint64 hour20 = 26;</code>
             */
            public Builder setHour20(long value) {

                hour20_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 hour20 = 26;</code>
             */
            public Builder clearHour20() {

                hour20_ = 0L;
                onChanged();
                return this;
            }

            private long hour21_;

            /**
             * <code>uint64 hour21 = 27;</code>
             */
            public long getHour21() {
                return hour21_;
            }

            /**
             * <code>uint64 hour21 = 27;</code>
             */
            public Builder setHour21(long value) {

                hour21_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 hour21 = 27;</code>
             */
            public Builder clearHour21() {

                hour21_ = 0L;
                onChanged();
                return this;
            }

            private long hour22_;

            /**
             * <code>uint64 hour22 = 28;</code>
             */
            public long getHour22() {
                return hour22_;
            }

            /**
             * <code>uint64 hour22 = 28;</code>
             */
            public Builder setHour22(long value) {

                hour22_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 hour22 = 28;</code>
             */
            public Builder clearHour22() {

                hour22_ = 0L;
                onChanged();
                return this;
            }

            private long hour23_;

            /**
             * <code>uint64 hour23 = 29;</code>
             */
            public long getHour23() {
                return hour23_;
            }

            /**
             * <code>uint64 hour23 = 29;</code>
             */
            public Builder setHour23(long value) {

                hour23_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 hour23 = 29;</code>
             */
            public Builder clearHour23() {

                hour23_ = 0L;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:io.union.log.common.proto.StatHourIpMessage)
        }

        // @@protoc_insertion_point(class_scope:io.union.log.common.proto.StatHourIpMessage)
        private static final io.union.log.common.proto.StatHourIpProto.StatHourIpMessage DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new io.union.log.common.proto.StatHourIpProto.StatHourIpMessage();
        }

        public static io.union.log.common.proto.StatHourIpProto.StatHourIpMessage getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<StatHourIpMessage>
                PARSER = new com.google.protobuf.AbstractParser<StatHourIpMessage>() {
            public StatHourIpMessage parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new StatHourIpMessage(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<StatHourIpMessage> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<StatHourIpMessage> getParserForType() {
            return PARSER;
        }

        public io.union.log.common.proto.StatHourIpProto.StatHourIpMessage getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_io_union_log_common_proto_StatHourIpMessage_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_io_union_log_common_proto_StatHourIpMessage_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\020StatHourIp.proto\022\031io.union.log.common." +
                        "proto\"\324\003\n\021StatHourIpMessage\022\n\n\002id\030\001 \001(\004\022" +
                        "\013\n\003uid\030\002 \001(\004\022\016\n\006siteid\030\003 \001(\004\022\016\n\006planid\030\004" +
                        " \001(\004\022\020\n\010add_time\030\005 \001(\004\022\r\n\005hour0\030\006 \001(\004\022\r\n" +
                        "\005hour1\030\007 \001(\004\022\r\n\005hour2\030\010 \001(\004\022\r\n\005hour3\030\t \001" +
                        "(\004\022\r\n\005hour4\030\n \001(\004\022\r\n\005hour5\030\013 \001(\004\022\r\n\005hour" +
                        "6\030\014 \001(\004\022\r\n\005hour7\030\r \001(\004\022\r\n\005hour8\030\016 \001(\004\022\r\n" +
                        "\005hour9\030\017 \001(\004\022\016\n\006hour10\030\020 \001(\004\022\016\n\006hour11\030\021" +
                        " \001(\004\022\016\n\006hour12\030\022 \001(\004\022\016\n\006hour13\030\023 \001(\004\022\016\n\006" +
                        "hour14\030\024 \001(\004\022\016\n\006hour15\030\025 \001(\004\022\016\n\006hour16\030\026",
                " \001(\004\022\016\n\006hour17\030\027 \001(\004\022\016\n\006hour18\030\030 \001(\004\022\016\n\006" +
                        "hour19\030\031 \001(\004\022\016\n\006hour20\030\032 \001(\004\022\016\n\006hour21\030\033" +
                        " \001(\004\022\016\n\006hour22\030\034 \001(\004\022\016\n\006hour23\030\035 \001(\004B,\n\031" +
                        "io.union.log.common.protoB\017StatHourIpPro" +
                        "tob\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_io_union_log_common_proto_StatHourIpMessage_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_io_union_log_common_proto_StatHourIpMessage_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_io_union_log_common_proto_StatHourIpMessage_descriptor,
                new java.lang.String[]{"Id", "Uid", "Siteid", "Planid", "AddTime", "Hour0", "Hour1", "Hour2", "Hour3", "Hour4", "Hour5", "Hour6", "Hour7", "Hour8", "Hour9", "Hour10", "Hour11", "Hour12", "Hour13", "Hour14", "Hour15", "Hour16", "Hour17", "Hour18", "Hour19", "Hour20", "Hour21", "Hour22", "Hour23",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
