// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UnionStats.proto

package io.union.log.common.proto;

public final class UnionStatsProto {
    private UnionStatsProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface UnionStatsMessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:io.union.log.common.proto.UnionStatsMessage)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>uint64 id = 1;</code>
         */
        long getId();

        /**
         * <code>uint64 views = 2;</code>
         */
        long getViews();

        /**
         * <code>uint64 clicks = 3;</code>
         */
        long getClicks();

        /**
         * <code>uint64 clickip = 4;</code>
         */
        long getClickip();

        /**
         * <code>uint64 uid = 5;</code>
         */
        long getUid();

        /**
         * <code>uint64 planid = 6;</code>
         */
        long getPlanid();

        /**
         * <code>uint64 adid = 7;</code>
         */
        long getAdid();

        /**
         * <code>uint64 advid = 8;</code>
         */
        long getAdvid();

        /**
         * <code>uint64 siteid = 9;</code>
         */
        long getSiteid();

        /**
         * <code>uint64 zoneid = 10;</code>
         */
        long getZoneid();

        /**
         * <code>uint32 paytype = 11;</code>
         */
        int getPaytype();

        /**
         * <code>uint64 paynum = 12;</code>
         */
        long getPaynum();

        /**
         * <code>uint64 dedunum = 13;</code>
         */
        long getDedunum();

        /**
         * <code>double sumpay = 14;</code>
         */
        double getSumpay();

        /**
         * <code>double sumadvpay = 15;</code>
         */
        double getSumadvpay();

        /**
         * <code>double sumprofit = 16;</code>
         */
        double getSumprofit();

        /**
         * <code>uint64 add_time = 17;</code>
         */
        long getAddTime();
    }

    /**
     * Protobuf type {@code io.union.log.common.proto.UnionStatsMessage}
     */
    public static final class UnionStatsMessage extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:io.union.log.common.proto.UnionStatsMessage)
            UnionStatsMessageOrBuilder {
        // Use UnionStatsMessage.newBuilder() to construct.
        private UnionStatsMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private UnionStatsMessage() {
            id_ = 0L;
            views_ = 0L;
            clicks_ = 0L;
            clickip_ = 0L;
            uid_ = 0L;
            planid_ = 0L;
            adid_ = 0L;
            advid_ = 0L;
            siteid_ = 0L;
            zoneid_ = 0L;
            paytype_ = 0;
            paynum_ = 0L;
            dedunum_ = 0L;
            sumpay_ = 0D;
            sumadvpay_ = 0D;
            sumprofit_ = 0D;
            addTime_ = 0L;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private UnionStatsMessage(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            id_ = input.readUInt64();
                            break;
                        }
                        case 16: {

                            views_ = input.readUInt64();
                            break;
                        }
                        case 24: {

                            clicks_ = input.readUInt64();
                            break;
                        }
                        case 32: {

                            clickip_ = input.readUInt64();
                            break;
                        }
                        case 40: {

                            uid_ = input.readUInt64();
                            break;
                        }
                        case 48: {

                            planid_ = input.readUInt64();
                            break;
                        }
                        case 56: {

                            adid_ = input.readUInt64();
                            break;
                        }
                        case 64: {

                            advid_ = input.readUInt64();
                            break;
                        }
                        case 72: {

                            siteid_ = input.readUInt64();
                            break;
                        }
                        case 80: {

                            zoneid_ = input.readUInt64();
                            break;
                        }
                        case 88: {

                            paytype_ = input.readUInt32();
                            break;
                        }
                        case 96: {

                            paynum_ = input.readUInt64();
                            break;
                        }
                        case 104: {

                            dedunum_ = input.readUInt64();
                            break;
                        }
                        case 113: {

                            sumpay_ = input.readDouble();
                            break;
                        }
                        case 121: {

                            sumadvpay_ = input.readDouble();
                            break;
                        }
                        case 129: {

                            sumprofit_ = input.readDouble();
                            break;
                        }
                        case 136: {

                            addTime_ = input.readUInt64();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return io.union.log.common.proto.UnionStatsProto.internal_static_io_union_log_common_proto_UnionStatsMessage_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return io.union.log.common.proto.UnionStatsProto.internal_static_io_union_log_common_proto_UnionStatsMessage_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            io.union.log.common.proto.UnionStatsProto.UnionStatsMessage.class, io.union.log.common.proto.UnionStatsProto.UnionStatsMessage.Builder.class);
        }

        public static final int ID_FIELD_NUMBER = 1;
        private long id_;

        /**
         * <code>uint64 id = 1;</code>
         */
        public long getId() {
            return id_;
        }

        public static final int VIEWS_FIELD_NUMBER = 2;
        private long views_;

        /**
         * <code>uint64 views = 2;</code>
         */
        public long getViews() {
            return views_;
        }

        public static final int CLICKS_FIELD_NUMBER = 3;
        private long clicks_;

        /**
         * <code>uint64 clicks = 3;</code>
         */
        public long getClicks() {
            return clicks_;
        }

        public static final int CLICKIP_FIELD_NUMBER = 4;
        private long clickip_;

        /**
         * <code>uint64 clickip = 4;</code>
         */
        public long getClickip() {
            return clickip_;
        }

        public static final int UID_FIELD_NUMBER = 5;
        private long uid_;

        /**
         * <code>uint64 uid = 5;</code>
         */
        public long getUid() {
            return uid_;
        }

        public static final int PLANID_FIELD_NUMBER = 6;
        private long planid_;

        /**
         * <code>uint64 planid = 6;</code>
         */
        public long getPlanid() {
            return planid_;
        }

        public static final int ADID_FIELD_NUMBER = 7;
        private long adid_;

        /**
         * <code>uint64 adid = 7;</code>
         */
        public long getAdid() {
            return adid_;
        }

        public static final int ADVID_FIELD_NUMBER = 8;
        private long advid_;

        /**
         * <code>uint64 advid = 8;</code>
         */
        public long getAdvid() {
            return advid_;
        }

        public static final int SITEID_FIELD_NUMBER = 9;
        private long siteid_;

        /**
         * <code>uint64 siteid = 9;</code>
         */
        public long getSiteid() {
            return siteid_;
        }

        public static final int ZONEID_FIELD_NUMBER = 10;
        private long zoneid_;

        /**
         * <code>uint64 zoneid = 10;</code>
         */
        public long getZoneid() {
            return zoneid_;
        }

        public static final int PAYTYPE_FIELD_NUMBER = 11;
        private int paytype_;

        /**
         * <code>uint32 paytype = 11;</code>
         */
        public int getPaytype() {
            return paytype_;
        }

        public static final int PAYNUM_FIELD_NUMBER = 12;
        private long paynum_;

        /**
         * <code>uint64 paynum = 12;</code>
         */
        public long getPaynum() {
            return paynum_;
        }

        public static final int DEDUNUM_FIELD_NUMBER = 13;
        private long dedunum_;

        /**
         * <code>uint64 dedunum = 13;</code>
         */
        public long getDedunum() {
            return dedunum_;
        }

        public static final int SUMPAY_FIELD_NUMBER = 14;
        private double sumpay_;

        /**
         * <code>double sumpay = 14;</code>
         */
        public double getSumpay() {
            return sumpay_;
        }

        public static final int SUMADVPAY_FIELD_NUMBER = 15;
        private double sumadvpay_;

        /**
         * <code>double sumadvpay = 15;</code>
         */
        public double getSumadvpay() {
            return sumadvpay_;
        }

        public static final int SUMPROFIT_FIELD_NUMBER = 16;
        private double sumprofit_;

        /**
         * <code>double sumprofit = 16;</code>
         */
        public double getSumprofit() {
            return sumprofit_;
        }

        public static final int ADD_TIME_FIELD_NUMBER = 17;
        private long addTime_;

        /**
         * <code>uint64 add_time = 17;</code>
         */
        public long getAddTime() {
            return addTime_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (id_ != 0L) {
                output.writeUInt64(1, id_);
            }
            if (views_ != 0L) {
                output.writeUInt64(2, views_);
            }
            if (clicks_ != 0L) {
                output.writeUInt64(3, clicks_);
            }
            if (clickip_ != 0L) {
                output.writeUInt64(4, clickip_);
            }
            if (uid_ != 0L) {
                output.writeUInt64(5, uid_);
            }
            if (planid_ != 0L) {
                output.writeUInt64(6, planid_);
            }
            if (adid_ != 0L) {
                output.writeUInt64(7, adid_);
            }
            if (advid_ != 0L) {
                output.writeUInt64(8, advid_);
            }
            if (siteid_ != 0L) {
                output.writeUInt64(9, siteid_);
            }
            if (zoneid_ != 0L) {
                output.writeUInt64(10, zoneid_);
            }
            if (paytype_ != 0) {
                output.writeUInt32(11, paytype_);
            }
            if (paynum_ != 0L) {
                output.writeUInt64(12, paynum_);
            }
            if (dedunum_ != 0L) {
                output.writeUInt64(13, dedunum_);
            }
            if (sumpay_ != 0D) {
                output.writeDouble(14, sumpay_);
            }
            if (sumadvpay_ != 0D) {
                output.writeDouble(15, sumadvpay_);
            }
            if (sumprofit_ != 0D) {
                output.writeDouble(16, sumprofit_);
            }
            if (addTime_ != 0L) {
                output.writeUInt64(17, addTime_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (id_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(1, id_);
            }
            if (views_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(2, views_);
            }
            if (clicks_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(3, clicks_);
            }
            if (clickip_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(4, clickip_);
            }
            if (uid_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(5, uid_);
            }
            if (planid_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(6, planid_);
            }
            if (adid_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(7, adid_);
            }
            if (advid_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(8, advid_);
            }
            if (siteid_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(9, siteid_);
            }
            if (zoneid_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(10, zoneid_);
            }
            if (paytype_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(11, paytype_);
            }
            if (paynum_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(12, paynum_);
            }
            if (dedunum_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(13, dedunum_);
            }
            if (sumpay_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(14, sumpay_);
            }
            if (sumadvpay_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(15, sumadvpay_);
            }
            if (sumprofit_ != 0D) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(16, sumprofit_);
            }
            if (addTime_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(17, addTime_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof io.union.log.common.proto.UnionStatsProto.UnionStatsMessage)) {
                return super.equals(obj);
            }
            io.union.log.common.proto.UnionStatsProto.UnionStatsMessage other = (io.union.log.common.proto.UnionStatsProto.UnionStatsMessage) obj;

            boolean result = true;
            result = result && (getId()
                    == other.getId());
            result = result && (getViews()
                    == other.getViews());
            result = result && (getClicks()
                    == other.getClicks());
            result = result && (getClickip()
                    == other.getClickip());
            result = result && (getUid()
                    == other.getUid());
            result = result && (getPlanid()
                    == other.getPlanid());
            result = result && (getAdid()
                    == other.getAdid());
            result = result && (getAdvid()
                    == other.getAdvid());
            result = result && (getSiteid()
                    == other.getSiteid());
            result = result && (getZoneid()
                    == other.getZoneid());
            result = result && (getPaytype()
                    == other.getPaytype());
            result = result && (getPaynum()
                    == other.getPaynum());
            result = result && (getDedunum()
                    == other.getDedunum());
            result = result && (
                    java.lang.Double.doubleToLongBits(getSumpay())
                            == java.lang.Double.doubleToLongBits(
                            other.getSumpay()));
            result = result && (
                    java.lang.Double.doubleToLongBits(getSumadvpay())
                            == java.lang.Double.doubleToLongBits(
                            other.getSumadvpay()));
            result = result && (
                    java.lang.Double.doubleToLongBits(getSumprofit())
                            == java.lang.Double.doubleToLongBits(
                            other.getSumprofit()));
            result = result && (getAddTime()
                    == other.getAddTime());
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getId());
            hash = (37 * hash) + VIEWS_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getViews());
            hash = (37 * hash) + CLICKS_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getClicks());
            hash = (37 * hash) + CLICKIP_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getClickip());
            hash = (37 * hash) + UID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getUid());
            hash = (37 * hash) + PLANID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getPlanid());
            hash = (37 * hash) + ADID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getAdid());
            hash = (37 * hash) + ADVID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getAdvid());
            hash = (37 * hash) + SITEID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getSiteid());
            hash = (37 * hash) + ZONEID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getZoneid());
            hash = (37 * hash) + PAYTYPE_FIELD_NUMBER;
            hash = (53 * hash) + getPaytype();
            hash = (37 * hash) + PAYNUM_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getPaynum());
            hash = (37 * hash) + DEDUNUM_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getDedunum());
            hash = (37 * hash) + SUMPAY_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getSumpay()));
            hash = (37 * hash) + SUMADVPAY_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getSumadvpay()));
            hash = (37 * hash) + SUMPROFIT_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    java.lang.Double.doubleToLongBits(getSumprofit()));
            hash = (37 * hash) + ADD_TIME_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getAddTime());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static io.union.log.common.proto.UnionStatsProto.UnionStatsMessage parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.union.log.common.proto.UnionStatsProto.UnionStatsMessage parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.union.log.common.proto.UnionStatsProto.UnionStatsMessage parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.union.log.common.proto.UnionStatsProto.UnionStatsMessage parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.union.log.common.proto.UnionStatsProto.UnionStatsMessage parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static io.union.log.common.proto.UnionStatsProto.UnionStatsMessage parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static io.union.log.common.proto.UnionStatsProto.UnionStatsMessage parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static io.union.log.common.proto.UnionStatsProto.UnionStatsMessage parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static io.union.log.common.proto.UnionStatsProto.UnionStatsMessage parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static io.union.log.common.proto.UnionStatsProto.UnionStatsMessage parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static io.union.log.common.proto.UnionStatsProto.UnionStatsMessage parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static io.union.log.common.proto.UnionStatsProto.UnionStatsMessage parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(io.union.log.common.proto.UnionStatsProto.UnionStatsMessage prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code io.union.log.common.proto.UnionStatsMessage}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:io.union.log.common.proto.UnionStatsMessage)
                io.union.log.common.proto.UnionStatsProto.UnionStatsMessageOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return io.union.log.common.proto.UnionStatsProto.internal_static_io_union_log_common_proto_UnionStatsMessage_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return io.union.log.common.proto.UnionStatsProto.internal_static_io_union_log_common_proto_UnionStatsMessage_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                io.union.log.common.proto.UnionStatsProto.UnionStatsMessage.class, io.union.log.common.proto.UnionStatsProto.UnionStatsMessage.Builder.class);
            }

            // Construct using io.union.log.common.proto.UnionStatsProto.UnionStatsMessage.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                id_ = 0L;

                views_ = 0L;

                clicks_ = 0L;

                clickip_ = 0L;

                uid_ = 0L;

                planid_ = 0L;

                adid_ = 0L;

                advid_ = 0L;

                siteid_ = 0L;

                zoneid_ = 0L;

                paytype_ = 0;

                paynum_ = 0L;

                dedunum_ = 0L;

                sumpay_ = 0D;

                sumadvpay_ = 0D;

                sumprofit_ = 0D;

                addTime_ = 0L;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return io.union.log.common.proto.UnionStatsProto.internal_static_io_union_log_common_proto_UnionStatsMessage_descriptor;
            }

            public io.union.log.common.proto.UnionStatsProto.UnionStatsMessage getDefaultInstanceForType() {
                return io.union.log.common.proto.UnionStatsProto.UnionStatsMessage.getDefaultInstance();
            }

            public io.union.log.common.proto.UnionStatsProto.UnionStatsMessage build() {
                io.union.log.common.proto.UnionStatsProto.UnionStatsMessage result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public io.union.log.common.proto.UnionStatsProto.UnionStatsMessage buildPartial() {
                io.union.log.common.proto.UnionStatsProto.UnionStatsMessage result = new io.union.log.common.proto.UnionStatsProto.UnionStatsMessage(this);
                result.id_ = id_;
                result.views_ = views_;
                result.clicks_ = clicks_;
                result.clickip_ = clickip_;
                result.uid_ = uid_;
                result.planid_ = planid_;
                result.adid_ = adid_;
                result.advid_ = advid_;
                result.siteid_ = siteid_;
                result.zoneid_ = zoneid_;
                result.paytype_ = paytype_;
                result.paynum_ = paynum_;
                result.dedunum_ = dedunum_;
                result.sumpay_ = sumpay_;
                result.sumadvpay_ = sumadvpay_;
                result.sumprofit_ = sumprofit_;
                result.addTime_ = addTime_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof io.union.log.common.proto.UnionStatsProto.UnionStatsMessage) {
                    return mergeFrom((io.union.log.common.proto.UnionStatsProto.UnionStatsMessage) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(io.union.log.common.proto.UnionStatsProto.UnionStatsMessage other) {
                if (other == io.union.log.common.proto.UnionStatsProto.UnionStatsMessage.getDefaultInstance())
                    return this;
                if (other.getId() != 0L) {
                    setId(other.getId());
                }
                if (other.getViews() != 0L) {
                    setViews(other.getViews());
                }
                if (other.getClicks() != 0L) {
                    setClicks(other.getClicks());
                }
                if (other.getClickip() != 0L) {
                    setClickip(other.getClickip());
                }
                if (other.getUid() != 0L) {
                    setUid(other.getUid());
                }
                if (other.getPlanid() != 0L) {
                    setPlanid(other.getPlanid());
                }
                if (other.getAdid() != 0L) {
                    setAdid(other.getAdid());
                }
                if (other.getAdvid() != 0L) {
                    setAdvid(other.getAdvid());
                }
                if (other.getSiteid() != 0L) {
                    setSiteid(other.getSiteid());
                }
                if (other.getZoneid() != 0L) {
                    setZoneid(other.getZoneid());
                }
                if (other.getPaytype() != 0) {
                    setPaytype(other.getPaytype());
                }
                if (other.getPaynum() != 0L) {
                    setPaynum(other.getPaynum());
                }
                if (other.getDedunum() != 0L) {
                    setDedunum(other.getDedunum());
                }
                if (other.getSumpay() != 0D) {
                    setSumpay(other.getSumpay());
                }
                if (other.getSumadvpay() != 0D) {
                    setSumadvpay(other.getSumadvpay());
                }
                if (other.getSumprofit() != 0D) {
                    setSumprofit(other.getSumprofit());
                }
                if (other.getAddTime() != 0L) {
                    setAddTime(other.getAddTime());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                io.union.log.common.proto.UnionStatsProto.UnionStatsMessage parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (io.union.log.common.proto.UnionStatsProto.UnionStatsMessage) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private long id_;

            /**
             * <code>uint64 id = 1;</code>
             */
            public long getId() {
                return id_;
            }

            /**
             * <code>uint64 id = 1;</code>
             */
            public Builder setId(long value) {

                id_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 id = 1;</code>
             */
            public Builder clearId() {

                id_ = 0L;
                onChanged();
                return this;
            }

            private long views_;

            /**
             * <code>uint64 views = 2;</code>
             */
            public long getViews() {
                return views_;
            }

            /**
             * <code>uint64 views = 2;</code>
             */
            public Builder setViews(long value) {

                views_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 views = 2;</code>
             */
            public Builder clearViews() {

                views_ = 0L;
                onChanged();
                return this;
            }

            private long clicks_;

            /**
             * <code>uint64 clicks = 3;</code>
             */
            public long getClicks() {
                return clicks_;
            }

            /**
             * <code>uint64 clicks = 3;</code>
             */
            public Builder setClicks(long value) {

                clicks_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 clicks = 3;</code>
             */
            public Builder clearClicks() {

                clicks_ = 0L;
                onChanged();
                return this;
            }

            private long clickip_;

            /**
             * <code>uint64 clickip = 4;</code>
             */
            public long getClickip() {
                return clickip_;
            }

            /**
             * <code>uint64 clickip = 4;</code>
             */
            public Builder setClickip(long value) {

                clickip_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 clickip = 4;</code>
             */
            public Builder clearClickip() {

                clickip_ = 0L;
                onChanged();
                return this;
            }

            private long uid_;

            /**
             * <code>uint64 uid = 5;</code>
             */
            public long getUid() {
                return uid_;
            }

            /**
             * <code>uint64 uid = 5;</code>
             */
            public Builder setUid(long value) {

                uid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 uid = 5;</code>
             */
            public Builder clearUid() {

                uid_ = 0L;
                onChanged();
                return this;
            }

            private long planid_;

            /**
             * <code>uint64 planid = 6;</code>
             */
            public long getPlanid() {
                return planid_;
            }

            /**
             * <code>uint64 planid = 6;</code>
             */
            public Builder setPlanid(long value) {

                planid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 planid = 6;</code>
             */
            public Builder clearPlanid() {

                planid_ = 0L;
                onChanged();
                return this;
            }

            private long adid_;

            /**
             * <code>uint64 adid = 7;</code>
             */
            public long getAdid() {
                return adid_;
            }

            /**
             * <code>uint64 adid = 7;</code>
             */
            public Builder setAdid(long value) {

                adid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 adid = 7;</code>
             */
            public Builder clearAdid() {

                adid_ = 0L;
                onChanged();
                return this;
            }

            private long advid_;

            /**
             * <code>uint64 advid = 8;</code>
             */
            public long getAdvid() {
                return advid_;
            }

            /**
             * <code>uint64 advid = 8;</code>
             */
            public Builder setAdvid(long value) {

                advid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 advid = 8;</code>
             */
            public Builder clearAdvid() {

                advid_ = 0L;
                onChanged();
                return this;
            }

            private long siteid_;

            /**
             * <code>uint64 siteid = 9;</code>
             */
            public long getSiteid() {
                return siteid_;
            }

            /**
             * <code>uint64 siteid = 9;</code>
             */
            public Builder setSiteid(long value) {

                siteid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 siteid = 9;</code>
             */
            public Builder clearSiteid() {

                siteid_ = 0L;
                onChanged();
                return this;
            }

            private long zoneid_;

            /**
             * <code>uint64 zoneid = 10;</code>
             */
            public long getZoneid() {
                return zoneid_;
            }

            /**
             * <code>uint64 zoneid = 10;</code>
             */
            public Builder setZoneid(long value) {

                zoneid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 zoneid = 10;</code>
             */
            public Builder clearZoneid() {

                zoneid_ = 0L;
                onChanged();
                return this;
            }

            private int paytype_;

            /**
             * <code>uint32 paytype = 11;</code>
             */
            public int getPaytype() {
                return paytype_;
            }

            /**
             * <code>uint32 paytype = 11;</code>
             */
            public Builder setPaytype(int value) {

                paytype_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint32 paytype = 11;</code>
             */
            public Builder clearPaytype() {

                paytype_ = 0;
                onChanged();
                return this;
            }

            private long paynum_;

            /**
             * <code>uint64 paynum = 12;</code>
             */
            public long getPaynum() {
                return paynum_;
            }

            /**
             * <code>uint64 paynum = 12;</code>
             */
            public Builder setPaynum(long value) {

                paynum_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 paynum = 12;</code>
             */
            public Builder clearPaynum() {

                paynum_ = 0L;
                onChanged();
                return this;
            }

            private long dedunum_;

            /**
             * <code>uint64 dedunum = 13;</code>
             */
            public long getDedunum() {
                return dedunum_;
            }

            /**
             * <code>uint64 dedunum = 13;</code>
             */
            public Builder setDedunum(long value) {

                dedunum_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 dedunum = 13;</code>
             */
            public Builder clearDedunum() {

                dedunum_ = 0L;
                onChanged();
                return this;
            }

            private double sumpay_;

            /**
             * <code>double sumpay = 14;</code>
             */
            public double getSumpay() {
                return sumpay_;
            }

            /**
             * <code>double sumpay = 14;</code>
             */
            public Builder setSumpay(double value) {

                sumpay_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double sumpay = 14;</code>
             */
            public Builder clearSumpay() {

                sumpay_ = 0D;
                onChanged();
                return this;
            }

            private double sumadvpay_;

            /**
             * <code>double sumadvpay = 15;</code>
             */
            public double getSumadvpay() {
                return sumadvpay_;
            }

            /**
             * <code>double sumadvpay = 15;</code>
             */
            public Builder setSumadvpay(double value) {

                sumadvpay_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double sumadvpay = 15;</code>
             */
            public Builder clearSumadvpay() {

                sumadvpay_ = 0D;
                onChanged();
                return this;
            }

            private double sumprofit_;

            /**
             * <code>double sumprofit = 16;</code>
             */
            public double getSumprofit() {
                return sumprofit_;
            }

            /**
             * <code>double sumprofit = 16;</code>
             */
            public Builder setSumprofit(double value) {

                sumprofit_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double sumprofit = 16;</code>
             */
            public Builder clearSumprofit() {

                sumprofit_ = 0D;
                onChanged();
                return this;
            }

            private long addTime_;

            /**
             * <code>uint64 add_time = 17;</code>
             */
            public long getAddTime() {
                return addTime_;
            }

            /**
             * <code>uint64 add_time = 17;</code>
             */
            public Builder setAddTime(long value) {

                addTime_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>uint64 add_time = 17;</code>
             */
            public Builder clearAddTime() {

                addTime_ = 0L;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:io.union.log.common.proto.UnionStatsMessage)
        }

        // @@protoc_insertion_point(class_scope:io.union.log.common.proto.UnionStatsMessage)
        private static final io.union.log.common.proto.UnionStatsProto.UnionStatsMessage DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new io.union.log.common.proto.UnionStatsProto.UnionStatsMessage();
        }

        public static io.union.log.common.proto.UnionStatsProto.UnionStatsMessage getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<UnionStatsMessage>
                PARSER = new com.google.protobuf.AbstractParser<UnionStatsMessage>() {
            public UnionStatsMessage parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new UnionStatsMessage(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<UnionStatsMessage> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<UnionStatsMessage> getParserForType() {
            return PARSER;
        }

        public io.union.log.common.proto.UnionStatsProto.UnionStatsMessage getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_io_union_log_common_proto_UnionStatsMessage_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_io_union_log_common_proto_UnionStatsMessage_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\020UnionStats.proto\022\031io.union.log.common." +
                        "proto\"\243\002\n\021UnionStatsMessage\022\n\n\002id\030\001 \001(\004\022" +
                        "\r\n\005views\030\002 \001(\004\022\016\n\006clicks\030\003 \001(\004\022\017\n\007clicki" +
                        "p\030\004 \001(\004\022\013\n\003uid\030\005 \001(\004\022\016\n\006planid\030\006 \001(\004\022\014\n\004" +
                        "adid\030\007 \001(\004\022\r\n\005advid\030\010 \001(\004\022\016\n\006siteid\030\t \001(" +
                        "\004\022\016\n\006zoneid\030\n \001(\004\022\017\n\007paytype\030\013 \001(\r\022\016\n\006pa" +
                        "ynum\030\014 \001(\004\022\017\n\007dedunum\030\r \001(\004\022\016\n\006sumpay\030\016 " +
                        "\001(\001\022\021\n\tsumadvpay\030\017 \001(\001\022\021\n\tsumprofit\030\020 \001(" +
                        "\001\022\020\n\010add_time\030\021 \001(\004B,\n\031io.union.log.comm" +
                        "on.protoB\017UnionStatsProtob\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_io_union_log_common_proto_UnionStatsMessage_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_io_union_log_common_proto_UnionStatsMessage_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_io_union_log_common_proto_UnionStatsMessage_descriptor,
                new java.lang.String[]{"Id", "Views", "Clicks", "Clickip", "Uid", "Planid", "Adid", "Advid", "Siteid", "Zoneid", "Paytype", "Paynum", "Dedunum", "Sumpay", "Sumadvpay", "Sumprofit", "AddTime",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
